### ISSUE TITLE
user-preload-script not automatically included

### ISSUE THREAD

**Issue by dallastjames** [capacitor-community/electron#107]
**Describe the bug**
In a new repo, the user-preload-script.js file is not automatically included in the build as expected. Changing the preload in the index.ts of the electron project to point to it will get it to load as expected, but comes at the cost of not loading the electron-rt.

**To Reproduce**
[Sample Project](https://github.com/dallastjames/cap-electron-preload-bug)

See index.ts in the electron folder for comments around the preload. When serving the project with `npx cap open @capacitor-community/electron` the default value will not log the value in the preload file. Changing to reference the preload directly will cause the value to be logged at runtime. 

**Expected behavior**
The user-preload-script.js file automatically included as part of the preload at runtime without needing to change the preload value in the index.ts

**Desktop (please complete the following information):**

- OS: Windows (WSL)/MacOS
- Version: @capacitor-community/electron@3.0.1

**Comment by IT-MikeS** [comment]
fixed in v4 (v3 will be deprecated)

**Comment by zachnamyat** [comment]
Hey @IT-MikeS , is there a way to work around this in version 3.0.1 or do I have to use version 4?
