### ISSUE TITLE
Can't build project (CRA + Cap 3 + sqlite)

### ISSUE THREAD

**Issue by agonzalezjr** [capacitor-community/electron#109]
**Describe the bug**

Started with a simple create-react-app and installed Capacitor in it (v3). `ios` platform works fine, but I can't get the `electron` platform working **after** adding the sqlite community plugin. Am I missing something or using the wrong version somewhere?

Looking at the sqlite plugin docs, it looks like they might not be ready for Electron + Capacitor v3 yet ... is there a way to specify that I only want to use this plugin for iOS/Android and not for Electron?

**To Reproduce**

```
$ npx create-react-app react-electron --template typescript
$ cd react-electron/
$ yarn add @capacitor/core @capacitor/cli
$ npx cap init
$ yarn add @capacitor/ios
$ npx cap add ios
# all good ✅
```
```
$ yarn add @capacitor-community/electron
$ npx cap add @capacitor-community/electron
$ npx cap open @capacitor-community/electron
# all good ✅
```
```
$ yarn add @capacitor-community/sqlite
$ npx cap sync @capacitor-community/electron
✔ Copying Web App to Electron platform in 32.38ms
⠋ Updating Electron plugins
Will install: @capacitor-community/sqlite@3.0.0
✔ Updating Electron plugins in 8.19s
# all good ✅
```

```
$ npx cap doctor @capacitor-community/electron
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.0
  @capacitor/core: 3.0.2
  @capacitor/android: 3.0.2
  @capacitor/ios: 3.1.0

Installed Dependencies:

  @capacitor/android: not installed
  @capacitor/cli: 3.1.0
  @capacitor/core: 3.0.2
  @capacitor/ios: 3.1.0

[error] Invalid platform: @capacitor-community/electron 
# this is strange 🤔
```
```
$ cd electron
$ npm run electron:start

> react-electron@1.0.0 electron:start /Users/agonzalezjr/code/react-electron/electron
> npm run build && electron ./


> react-electron@1.0.0 build /Users/agonzalezjr/code/react-electron/electron
> tsc

CapacitorCommunitySqlite
   CapacitorSQLite
    ["isSecretStored","setEncryptionSecret","changeEncryptionSecret","createConnection","closeConnection","echo","open","close","execute","executeSet","run","query","isDBExists","isDBOpen","isDatabase","isTableExists","deleteDatabase","isJsonValid","importFromJson","exportToJson","createSyncTable","setSyncDate","getSyncDate","addUpgradeStatement","copyFromAssets","getDatabaseList","addSQLiteSuffix","deleteOldDatabases","checkConnectionsConsistency"]

(node:13008) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at Object.setupCapacitorElectronPlugins (/Users/agonzalezjr/code/react-electron/electron/node_modules/@capacitor-community/electron/dist/core/util.js:98:41)
    at ElectronCapacitorApp.init (/Users/agonzalezjr/code/react-electron/electron/build/src/index.js:102:20)
    at /Users/agonzalezjr/code/react-electron/electron/build/src/index.js:127:26
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:13008) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by agonzalezjr** [comment]
Env: macOS 11.4

```
$ node --version && npm --version
v14.17.0
6.14.13
```

**Comment by IT-MikeS** [comment]
I believe this is due to the plug-in itself but I do know that it will be working with the release of v4 of this platform coming soon.

**Comment by dwaw18** [comment]
Similar problem here. I’ve developed custom plugin based on example Device plugin included in this repository.

After adding plugin to my main Capacitor project and syncing it with Electron, Electron app doesn’t run and exact same error as @agonzalezjr is thrown. 

```
(node:21604) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at Object.setupCapacitorElectronPlugins `(electron\node_modules\@capacitor-community\electron\dist\core\util.js:98:41)`
    at ElectronCapacitorApp.init (electron\build\src\index.js:102:20)
    at electron\build\src\index.js:129:26
```

I’ve done some digging (by putting console.log in file \electron\dist\core\util.js in place where error occurs) 

Modified beggining function setupCapacitorElectronPlugins() in utils.js, which only has added and rearranged console.logs

```
function setupCapacitorElectronPlugins() {
    //setupListeners
    const rtPluginsPath = path_1.join(electron_1.app.getAppPath(), "node_modules", "@capacitor-community", "electron", "dist", "runtime", "electron-plugins.js");
    // eslint-disable-next-line @typescript-eslint/no-empty-function
    const AsyncFunction = (async () => { }).constructor;
    const plugins = require(rtPluginsPath);

    console.log('plugins |', plugins);

    const pluginFunctionsRegistry = {};
    for (const pluginKey of Object.keys(plugins)) {
        console.log('pluginKey |', pluginKey);
        console.log('plugins[pluginKey] |', plugins[pluginKey]);
        for (const classKey of Object.keys(plugins[pluginKey])) {
            console.log('classKey |', classKey);
            console.log('(plugins[pluginKey][classKey] |', plugins[pluginKey][classKey]);
            console.log('plugins[pluginKey][classKey].prototype |', plugins[pluginKey][classKey].prototype);

            const functionList = Object.getOwnPropertyNames(plugins[pluginKey][classKey].prototype).filter(v => v !== 'constructor');
            console.log('    ' + JSON.stringify(functionList));
            console.log('');
            if (!pluginFunctionsRegistry[classKey]) {
                pluginFunctionsRegistry[classKey] = {};
            }
```

And this is the output:

```
plugins | {
  MyOrgCapacitorPluginWifi: {
    CustomWifi: [class CustomWifi],
    default: { CustomWifi: [class CustomWifi] }
  }
}

pluginKey | MyOrgCapacitorPluginWifi

plugins[pluginKey] | {
  CustomWifi: [class CustomWifi],
  default: { CustomWifi: [class CustomWifi] }
}

classKey | CustomWifi

(plugins[pluginKey][classKey] | [class CustomWifi]
plugins[pluginKey][classKey].prototype | {}
    ["getWifiBroadcastIp"]

classKey | default

(plugins[pluginKey][classKey] | { CustomWifi: [class CustomWifi] }

plugins[pluginKey][classKey].prototype | undefined

(node:15000) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
```

As you can see, this function iterates through object, which has property **default** with value of new object containing plugin information. This new object doesn't have **prototype** property (classKey), which causes Error when calling function Object.getOwnPropertyNames

Possible solution: remove reference to prototype property by replacing
` const functionList = Object.getOwnPropertyNames(plugins[pluginKey][classKey].prototype).filter(v => v !== 'constructor');`
to
` const functionList = Object.getOwnPropertyNames(plugins[pluginKey][classKey]).filter(v => v !== 'constructor');`

or remove **default** property from plugins[pluginKey].

My Env: 
```
Windows 10 Pro 21H1, Build 19043.1165

"@capacitor-community/electron": "3.0.2"

node –version
v14.17.4

npm –version
6.14.14
```

**Comment by IT-MikeS** [comment]
@dwaw18 try on version `3.0.3` that I just released 👍

**Comment by dwaw18** [comment]
@IT-MikeS Unfortunately it doesn't work. From commits in this repository I can see that fix was applied to electron-rt.ts was applied, but probably this exact fix should also be applied to core/util.ts in method setupCapacitorElectronPlugins() as I described in my previous comment.

While opening Electron, which executes setupCapacitorElectronPlugins(), plugins[pluginKey] with my plugin object still has **default** property.

```
plugins {
  MyOrgCapacitorPluginWifi: {
    CustomWifi: [class CustomWifi],
    default: { CustomWifi: [class CustomWifi] }
  }
}
```

**Comment by IT-MikeS** [comment]
> @IT-MikeS Unfortunately it doesn't work. From commits in this repository I can see that fix was applied to electron-rt.ts was applied, but probably this exact fix should also be applied to core/util.ts in method setupCapacitorElectronPlugins() as I described in my previous comment.
> 
> While opening Electron, which executes setupCapacitorElectronPlugins(), plugins[pluginKey] with my plugin object still has **default** property.
> 
> ```
> plugins {
>   MyOrgCapacitorPluginWifi: {
>     CustomWifi: [class CustomWifi],
>     default: { CustomWifi: [class CustomWifi] }
>   }
> }
> ```

Yep I missed fixing it in the main side of the plugin system, but fixed it in the runtime side 🤦‍♂️

**Comment by dwaw18** [comment]
@IT-MikeS I can happily confirm that now Electron app openes! 😃 

However, there is another issue: when I'm calling plugin function from electron, runtime side after hanging for like 3-5 seconds returns object 
`{error: "reply was never sent"}`

and main side throws Error 
```
(node:8852) UnhandledPromiseRejectionWarning: Error: An object could not be cloned.
    at Object.set (electron/js2c/browser_init.js:161:9964)
    at IpcMainImpl.<anonymous> (electron\node_modules\@capacitor-community\electron\dist\core\util.js:124:47)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10099)
    at Object.emit (events.js:315:20)
(node:8852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To te
rminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

In my plugin implementation for Electron, I'm creating object with one property and using Promise.resolve to pass it to Capacitor.

```
export class CustomWifi implements CustomWifiPlugin {
    getWifiBroadcastIp(): Promise<WifiBroadCastIpResponse> {
        const ip: WifiBroadCastIpResponse = {
            value: '192.168.0.255'
        }

        return Promise.resolve(ip);
    }
}
```

This plugin function getWifiBroadcastIp() is itself called, because I can see a console.log message in console when I put it before returning Promise.resolve.

**Comment by dwaw18** [comment]
@IT-MikeS I've created one at https://github.com/dwaw18/nextjs-electron-capacitor-sample 

In UI, go to http://localhost:3000/plugin to test if it prints response correctly. 

Commands:

```
yarn dev - starts Next.JS dev environment, accessible through browser.
yarn build:electron - builds app to be used for Electron
yarn electron:open - opens electron app
```

You probably will need to publish plugin to GitHub npm registry, because `yarn build:electron` will fail. . In my project I've done it for GitLab repository, but unfortunately project itseft and package is private and I don't have time today to also publish plugin as separate package to npm/GitHub registry.

**Comment by digaus** [comment]
@dwaw18 @IT-MikeS 
It seems to be something with Promises. I also ran into this issue with my plugins. First it worked, but now it does not. 

Of my Wifi plugin, `getIP` ist working fine but `getSSID` for example is not.

Also I cannot install plugins with a reference to a git repo because when trying to call `npx cap sync` it always looks for a npm published version.

I do not know what changed but everytime I use a Promise inside my Electron plugin, the call either throws the error below or does not resolve at all as mentioned above
```
(node:20328) UnhandledPromiseRejectionWarning: Error: Command failed: netsh wlan show interfaces

    at ChildProcess.exithandler (child_process.js:317:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:20328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
You can clone my repos and try it out.

**Comment by IT-MikeS** [comment]
Could you try with the 3.0.4 version of the platform, just curious if it has to do with the changes in the API

**Comment by digaus** [comment]
> Could you try with the 3.0.4 version of the platform, just curious if it has to do with the changes in the API

Will do. In an hour I or so I can report back :)

**Comment by digaus** [comment]
@IT-MikeS 
3.0.4 also not working :/ You can try my capacitor-plugin-demo with my wifi plugin for example

**Comment by jepiqueau** [comment]
@digaus I finally succeed to update the electron part of the @capacitor-community/sqlite by using @capacitor/core@3.2.0 and @capacitor-community/electron@3.1.0 look ar the release 3.2.0-2 of the plug-in and the angular-sqlite-app-starter for implementation. As you mentioned we work blind as throwing errors do not go through the bridge. Hope it may help you

**Comment by digaus** [comment]
> @digaus I finally succeed to update the electron part of the @capacitor-community/sqlite by using @capacitor/core@3.2.0 and @capacitor-community/electron@3.1.0 look ar the release 3.2.0-2 of the plug-in and the angular-sqlite-app-starter for implementation. As you mentioned we work blind as throwing errors do not go through the bridge. Hope it may help you

Thanks for the reply. Yes this is a strange issue. Unfortunately I cannot test of the promise for my WiFi plugin resolved because of the other issue I experienced
https://github.com/capacitor-community/electron/issues/135

I am developing in a VM with Hyper-V which obviously does not have a WiFi connection. And since the resulting .exe does not work on a different system I cannot test it :/

**Comment by digaus** [comment]
Now tried V4 and updated my plugins. Now only the web implementation ist called :/

**Comment by jepiqueau** [comment]
@digaus yes this is why I fall back this morning to 3.1.0 I told Mike yesterday about it on the contributors slack channel

**Comment by digaus** [comment]
> @digaus yes this is why I fall back this morning to 3.1.0 I told Mike yesterday about it on the contributors slack channel

Yeah seems I have to wait anyway for now because of https://github.com/capacitor-community/electron/issues/135

**Comment by IT-MikeS** [comment]
Yeah sorry there was a change in plugin load methodology, I do have examples in the repo of functioning plugins, they may be of assistance.

As for the promise resolution issues, can you guys describe a bit more what the flow is you'd like to see and I can see what I can do?

Sorry I haven't been super responsive on the repo lately, been a busy time in life

**Comment by digaus** [comment]
> Yeah sorry there was a change in plugin load methodology, I do have examples in the repo of functioning plugins, they may be of assistance.
> 
> As for the promise resolution issues, can you guys describe a bit more what the flow is you'd like to see and I can see what I can do? Perhaps in a new issue as I feel this one is a bit derailed and you have more specific questions/issues at this time?
> 
> Sorry I haven't been super responsive on the repo lately, been a busy time in life

I tried basing my plugin on the plugins listed in the example without success. They were not registered :/

For the promise as of now you cannot throw and error inside the plugin as it always results in an undhandled exception and does not get passed to the webview. We cannot even use  `.catch` because this results in another error.

We want to be able to handle exceptions inside the webview

**Comment by jepiqueau** [comment]
@digaus @IT-MikeS i install this morning the v4 but it is pointing to the plugin web implementation and not to the plugin electron implementation `window.CapacitorElectronPlugins` returned undefined. You can see that with the `angular-sqlite-app-starter` app. An other thing is that after installing the v4 when you `npx cap add @capacitor-community/electron` if you look at the `package.json` file in the electron folder it is using `@capacitor-community/electron@alpha` and not v4.

**Comment by jepiqueau** [comment]
@digaus @IT-MikeS It seems that with v4 , the throw of an error is now passing throw the webview or bridge as the application is not hanging anymore and i got `$$$ runTest failed Error: Not implemented on web` in the console.log

**Comment by digaus** [comment]
> @digaus @IT-MikeS i install this morning the v4 but it is pointing to the plugin web implementation and not to the plugin electron implementation `window.CapacitorElectronPlugins` returned undefined. You can see that with the `angular-sqlite-app-starter` app. An other thing is that after installing the v4 when you `npx cap add @capacitor-community/electron` if you look at the `package.json` file in the electron folder it is using `@capacitor-community/electron@alpha` and not v4.

Maybe you missed something:

Here is my commit for V4 -> https://github.com/digaus/community-capacitor-wifi/commit/b6b5f103269bd8d722c9e5dfbd519b889b129b71

**Comment by digaus** [comment]
@IT-MikeS 

This issue also happens with your demo Filesystem plugin:

```
Error occurred in handler for 'Filesystem-readFile': TypeError: Cannot read property 'sep' of undefined
    at Object.getCleanPath
```

**Comment by jepiqueau** [comment]
@IT-MikeS @digaus  In file `electron-rt.ts` this wrong as `${classKey}-${functionName}` is not evaluated ```
        contextApi[classKey][functionName] = (...args) =>
          ipcRenderer.invoke(`${classKey}-${functionName}`, ...args);
```
and then `contextApi[classKey] ` is {}

**Comment by IT-MikeS** [comment]
Are your plugins exporting a default or just exporting a class? The later is the required format

**Comment by jepiqueau** [comment]
@IT-MikeS @capacitor-community/sqlite is exporting a class
 ```
export class CapacitorSQLite implements CapacitorSQLitePlugin {
```
I did check that the classKey is correct and the functionName is correct if i do this 
```
    for (const functionName of functionList) {
      if (!contextApi[classKey][functionName]) {
        const fName = `${classKey}-${functionName}`;
        console.log(`fName: ${fName}`);
        contextApi[classKey][functionName] = (...args) => 
          ipcRenderer.invoke(fName, ...args);
      }
      console.log(`in loop contextApi: ${JSON.stringify(contextApi)}`);
    }
    console.log(`contextApi: ${JSON.stringify(contextApi)}`);
```
i got this
``` 
fName: CapacitorSQLite-isSecretStored
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-setEncryptionSecret
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-changeEncryptionSecret
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-createConnection
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-closeConnection
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-echo
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 
... 
fName: CapacitorSQLite-resetDbDict
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-symmetricDifference
VM77 electron-rt.js:20 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:22 contextApi: {"CapacitorSQLite":{}}
VM76 preload.js:4  
```

**Comment by IT-MikeS** [comment]
Odd by that log it's loading the plug-in methods fine but you are still getting the web impl?

**Comment by jepiqueau** [comment]
@IT-MikeS Yes because `ipcRenderer.invoke(fName, ...args);` does not evaluate fName you can see that if you replace it with `ipcRenderer.invoke(`${fName}`, ...args);`

**Comment by jepiqueau** [comment]
@IT-MikeS @digaus  Digaus suggests to add this in the index.ts file but it doesn't change anything
```
const CapacitorSQLite = registerPlugin<CapacitorSQLitePlugin>(
  'CapacitorSQLite',
  {
    web: () => import('./web').then(m => new m.CapacitorSQLiteWeb()),
    electron: () => (window as any).CapacitorCustomPlatform.plugins.CapacitorSQLite,
  },
);
```
It takes the web implementation as the contextApi is {} meaning that it does not have been filled with the ipcRenderer.invoke function

**Comment by IT-MikeS** [comment]
> @IT-MikeS @digaus Digaus suggests to add this in the index.ts file but it doesn't change anything
> 
> ```
> const CapacitorSQLite = registerPlugin<CapacitorSQLitePlugin>(
>   'CapacitorSQLite',
>   {
>     web: () => import('./web').then(m => new m.CapacitorSQLiteWeb()),
>     electron: () => (window as any).CapacitorCustomPlatform.plugins.CapacitorSQLite,
>   },
> );
> ```
> 
> It takes the web implementation as the contextApi is {} meaning that it does not have been filled with the ipcRenderer.invoke function

That line is required, yes, but I'm going to look into what might be going on here, I assume your main Cap-SQLite repo is good to test with?

**Comment by jepiqueau** [comment]
@IT-MikeS you can use the plugin @capacitor-community/sqlite and i use the `angular-sqlite-app-starter` to test it on this one after clone it you have to replace @capacitor-community/electron3.1.0 with 4.0 remove the electron platform.
```
run build
npx cap add @capacitor-community/electron
cd electron
npm i --save sqlite3
npm i --save-dev @types/sqlite3
npm build
npx cap copy
npx cap copy @capacitor-community/electron
npx cap open @capacitor-community/electron
```

**Comment by jepiqueau** [comment]
@IT-MikeS when the home page is there do not do anything in the interface go to the console and do window.CapacitorElectronPlugins and you should get undefined

**Comment by digaus** [comment]
> @IT-MikeS when the home page is there do not do anything in the interface go to the console and do window.CapacitorElectronPlugins and you should get undefined

What happens when you log `window.CapacitorCustomPlatform`?

**Comment by jepiqueau** [comment]
@IT-MikeS if i do this
```
    for (const functionName of functionList) {
      if (!contextApi[classKey][functionName]) {
        const fName = `${classKey}-${functionName}`;
        console.log(`fName: ${fName}`);
        contextApi[classKey][functionName] = (...args) => 
          ipcRenderer.invoke(`${fName}`, ...args);
        console.log(`contextApi[${classKey}][${functionName}] ${contextApi[classKey][functionName]}`)
      }
      console.log(`in loop contextApi: ${JSON.stringify(contextApi)}`);
    }
    console.log(`contextApi: ${JSON.stringify(contextApi)}`);
```
i got this
```
fName: CapacitorSQLite-isSecretStored
VM77 electron-rt.js:19 contextApi[CapacitorSQLite][isSecretStored] (...args) => electron_1.ipcRenderer.invoke(`${fName}`, ...args)
VM77 electron-rt.js:21 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-setEncryptionSecret
VM77 electron-rt.js:19 contextApi[CapacitorSQLite][setEncryptionSecret] (...args) => electron_1.ipcRenderer.invoke(`${fName}`, ...args)
VM77 electron-rt.js:21 in loop contextApi: {"CapacitorSQLite":{}}
VM77 electron-rt.js:17 fName: CapacitorSQLite-changeEncryptionSecret
VM77 electron-rt.js:19 contextApi[CapacitorSQLite][changeEncryptionSecret] (...args) => electron_1.ipcRenderer.invoke(`${fName}`, ...args)
VM77 electron-rt.js:21 
```
 you can see `electron_1.ipcRenderer.invoke(`${fName}`, ...args)` instead of the evaluate fName

**Comment by IT-MikeS** [comment]
> > @IT-MikeS when the home page is there do not do anything in the interface go to the console and do window.CapacitorElectronPlugins and you should get undefined
> 
> What happens when you log `window.CapacitorCustomPlatform`?
> 
> ![image](https://user-images.githubusercontent.com/15358538/130613943-a2bc5da7-f9d6-443b-a16e-1ca3baa09011.png)

Are your plugins now functioning?

**Comment by digaus** [comment]
> > > @IT-MikeS when the home page is there do not do anything in the interface go to the console and do window.CapacitorElectronPlugins and you should get undefined
> > 
> > 
> > What happens when you log `window.CapacitorCustomPlatform`?
> > ![image](https://user-images.githubusercontent.com/15358538/130613943-a2bc5da7-f9d6-443b-a16e-1ca3baa09011.png)
> 
> Are your plugins now functioning?

Not 100%. I am able to get SSID now (node-wifi dependency) but calling 'this' and node dependencies does not work:
-> `this`, `os`, `path` and `fs` etc. are all `undefined`

This also happens with your Filesystem Plugin
https://github.com/capacitor-community/electron/issues/109#issuecomment-904461796

**Comment by jepiqueau** [comment]
@IT-MikeS @digaus 
window.CapacitorCustomPlatform
{name: "electron", plugins: {…}}
name: "electron"
plugins:
CapacitorSQLite:
addSQLiteSuffix: ƒ ()
addUpgradeStatement: ƒ ()
changeEncryptionSecret: ƒ ()
checkConnectionsConsistency: ƒ ()
close: ƒ ()
closeConnection: ƒ ()
copyFromAssets: ƒ ()
createConnection: ƒ ()
createSyncTable: ƒ ()
deleteDatabase: ƒ ()
deleteOldDatabases: ƒ ()
echo: ƒ ()
execute: ƒ ()
executeSet: ƒ ()
exportToJson: ƒ ()
getDatabaseList: ƒ ()
getSyncDate: ƒ ()
importFromJson: ƒ ()
isDBExists: ƒ ()
isDBOpen: ƒ ()
isDatabase: ƒ ()
isJsonValid: ƒ ()
isSecretStored: ƒ ()
isTableExists: ƒ ()
open: ƒ ()
query: ƒ ()
resetDbDict: ƒ ()
run: ƒ ()
setEncryptionSecret: ƒ ()
setSyncDate: ƒ ()
symmetricDifference: ƒ ()
__proto__: Object
__proto__: Object
__proto__: Object
﻿
​

**Comment by digaus** [comment]
@jepiqueau 
Did you test with a local version of your plugin? Because your app-starter refers to an 19 hour old version (which I guess does not have `electron: () => (window as any).CapacitorCustomPlatform.plugins.CapacitorSQLite`)

**Comment by jepiqueau** [comment]
@digaus i test with a local version a the plugin where i add your recommendation in the index.ts file 
```
import { registerPlugin } from '@capacitor/core';

import type { CapacitorSQLitePlugin } from './definitions';

const CapacitorSQLite = registerPlugin<CapacitorSQLitePlugin>(
  'CapacitorSQLite',
  {
    web: () => import('./web').then(m => new m.CapacitorSQLiteWeb()),
    electron: () => (window as any).CapacitorCustomPlatform.plugins.CapacitorSQLite,
  },
);

export { CapacitorSQLite };
export * from './definitions';
```

**Comment by jepiqueau** [comment]
@digaus which version of electron are you using in the plugin ? i use 13.1.3 i do not have problem with path, fs, os if i use this as rollup.config.js
```
import commonjs from '@rollup/plugin-commonjs';
import nodeResolve from '@rollup/plugin-node-resolve';

export default {
  input: 'electron/build/electron/src/index.js',
  output: [
    {
      file: 'electron/dist/plugin.js',
      format: 'cjs',
      sourcemap: true,
      inlineDynamicImports: true,
      exports: 'named',
    },
  ],
  external: ['@capacitor/core', 'sqlite3'],
  plugins: [nodeResolve(), commonjs()],
};
```

**Comment by jepiqueau** [comment]
@IT-MikeS is the problem could be from exports: 'named' in the rollup.config.ts  of the plugin i was forced to use this as i use other classes in the plugin

**Comment by digaus** [comment]
@IT-MikeS 
No my plugin is also not being registered anymore and I do not know why ^^

**Comment by IT-MikeS** [comment]
Hey guys, please try with `4.0.2` I was able to get `sqlite` to register and run methods via the bridge but I dont have a `.db` file to test completely with so I'll leave that one with you.

**Comment by jepiqueau** [comment]
@IT-MikeS  Thanks, I will try tomorrow for me i have done too much computer today

**Comment by digaus** [comment]
Tried now.

My FileServer plugin is kinda running. My Wifi plugin however is still using the webimplementation. You can try yourself if you want:

https://github.com/digaus/capacitor-plugin-demo
https://github.com/digaus/community-capacitor-wifi/tree/capacitor3
https://github.com/digaus/community-capacitor-file-server/tree/capacitor3


FileServer is only kinda running as I get a nullpointer when trying to stop the server which I assigned to `this.server`

```
in setupCapacitorElectronPlugins
{
  CapacitorCommunityFileServer: {
    FileServer: [class FileServer],
    default: { FileServer: [class FileServer] }
  },
  CapacitorCommunityWifi: { Wifi: [class Wifi], default: { Wifi: [class Wifi] } }
}
CapacitorCommunityFileServer
-> FileServer
--> start
--> stop
CapacitorCommunityWifi
-> Wifi
--> getIP
--> getSSID
--> connect
--> connectPrefix
--> disconnect
--> checkConnection
--> timeout
--> insertSelect
--> reconnect
Skip checkForUpdatesAndNotify because application is not packed
called ipcMain.handle: FileServer-start
called ipcMain.handle: FileServer-stop
Error occurred in handler for 'FileServer-stop': TypeError: Cannot read property 'close' of null
    at C:\Users\User\Documents\Git\community-capacitor-file-server\electron\dist\plugin.js:43:25
```

**Comment by IT-MikeS** [comment]
A new object is instantiated every call to the plugin, the instance you are referencing does not exist. I can modify this behavior, would that be beneficial?

**Comment by digaus** [comment]
> A new object is instantiated every call to the plugin, the instance you are referencing does not exist. I can modify this behavior, would that be beneficial?

Well that's not something I expected. I think noone would expect that do changing it might be best.

Is there anything against it using only one instance?

Another thing I noticed is when I changed from `require` to `import` (`import http from 'http'`) it is `undefined` when trying to call it.

I also do not know why my WiFi plugin does not work.

**Comment by IT-MikeS** [comment]
@jepiqueau I have tested your plugin, via your test app and was successful with `v4.0.3` of the electron platform, however you will need to merge @digaus PR 

@digaus I submitted a PR to your file system plugin repo with fixes that make it function with `v4.0.3` and hopefully that can help your with your WiFi plugin too 

Thanks for all the feedback and patience fellas! 🙏

**Comment by jepiqueau** [comment]
@IT-MikeS @digaus Congrats to both of you, it works. It really pleasant to start the day which something working 😎 👍👏👏. I really appreciate and thanks you for the heavy work done.
One remark when you add the @capacitor-community/electron platform in the package.json file you get @capacitor-community/electron@4.0.1 it should be @capacitor-community/electron@4.0.3
I hope the developer's community will appreciate the work done. Hope @IT-MikeS you can relax a bit😅😅🤪😎 and go for a beer.
I will let @digaus to close the issue when everything will be tested on his side

**Comment by digaus** [comment]
@IT-MikeS 
Yes FileServer works now :) 

But still could not get Wifi Plugin to register the electron part ^^ its always calling the web implementation :/

This evening I will try with only Wifi Plugin and then if that does not work I will copy FileServer Plugin and rewrite my Wifi Plugin based on that.

**Comment by IT-MikeS** [comment]
> @IT-MikeS @digaus Congrats to both of you, it works. It really pleasant to start the day which something working 😎 👍👏👏. I really appreciate and thanks you for the heavy work done.
> One remark when you add the @capacitor-community/electron platform in the package.json file you get @capacitor-community/electron@4.0.1 it should be @capacitor-community/electron@4.0.3
> I hope the developer's community will appreciate the work done. Hope @IT-MikeS you can relax a bit😅😅🤪😎 and go for a beer.
> I will let @digaus to close the issue when everything will be tested on his side

Thank you and I'm glad its all working now 👍

**Comment by IT-MikeS** [comment]
> @IT-MikeS
> Yes FileServer works now, thank you :)
> 
> But still could not get Wifi Plugin to register the electron part ^^ its always calling the web implementation :/
> 
> This evening I will try with only Wifi Plugin and then if that does not work I will copy FileServer Plugin and rewrite my Wifi Plugin based on that.

I will try to have a look at it later tonight here too, but for now I'm going to close this issue 👍
