### ISSUE TITLE
Build process broken: Cannot find module 'electron-plugins.js'

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/electron#110]
**Describe the bug**
When I run `npm run build && electron ./` the following error occurs:

![Bildschirmfoto 2021-07-09 um 10 56 31](https://user-images.githubusercontent.com/1294854/125052517-562d4d80-e0a4-11eb-98c1-5ba57cb377da.png)

When I look further into the node_modules folder, there is no electron-plugins.js file.

![Bildschirmfoto 2021-07-09 um 10 56 56](https://user-images.githubusercontent.com/1294854/125052628-765d0c80-e0a4-11eb-9ab1-be7f7ada19a6.png)

But this file is required in `util.ts`, see: https://github.com/capacitor-community/electron/blob/f7e7574a38ba084ca1fa370e72373d0ab34c254a/src/electron/util.ts#L90

**Additional context**

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/ios: 3.1.1

Installed Dependencies:

  @capacitor/cli: 3.1.1
  @capacitor/android: 3.1.1
  @capacitor/core: 3.1.1
  @capacitor/ios: 3.1.1

package.json
```
 "dependencies": {
    "@capacitor-community/electron": "^3.0.0",
    "electron-context-menu": "^3.1.1",
    "electron-dl": "^3.2.1",
    "electron-is-dev": "~2.0.0",
    "electron-log": "^4.3.5",
    "electron-progressbar": "^2.0.1",
    "electron-serve": "~1.1.0",
    "electron-store": "^8.0.0",
    "electron-updater": "^4.3.9",
    "electron-window-state": "^5.0.3",
    "open": "^8.2.1"
  },
  "devDependencies": {
    "dotenv": "^10.0.0",
    "electron": "~13.1.3",
    "electron-builder": "~22.11.7",
    "electron-notarize": "^1.0.0",
    "electron-rebuild": "~2.3.5",
    "typescript": "~4.3.4"
  },
```

**Comment by zachnamyat** [comment]
Hello,

If you go into node_modules/@capacitor-community/electron/dist/cli-scripts/cap-scripts.js you will find the code related to creating the electron-plugins.js file. If you run `npx cap update electron` from one directory out, it should run the necessary command to create the file. I had this same issue two weeks ago and there is no answer online for it. Hopefully this helps you.

**Comment by IT-MikeS** [comment]
Yep in your main web app folder run `npx cap update @capacitor-community/electron` and it will generate that file, normally it's generated when you add the platform

**Comment by wvankoppen** [comment]
I exprience the same issue on both MacOs and Windows.  Running the suggested command `npx cap update @capacitor-community/electron` does not solve it.
 
Since the missing file is located in the node_modules folder, I would expect that the file is created when running `npm i`? Or does the capacitor update needs to be ran on each fresh install of the node modules?

My versions:

```
 "dependencies": {
        "@capacitor-community/electron": "^4.1.2",
        "electron-serve": "^1.1.0",
        "electron-is-dev": "^2.0.0",
        "electron-devtools-installer": "^3.2.0"
    },
    "devDependencies": {
        "electron": "^21.2.0",
        "electron-builder": "^23.6.0",
        "typescript": "~4.6.4",
        "electron-rebuild": "^3.2.9",
        "keyv": "^4.5.0"
    },
```
