### ISSUE TITLE
MacOs - no window

### ISSUE THREAD

**Issue by RouR** [capacitor-community/electron#111]
**Describe the bug**
I created a test project.

The application runs successfully in Windows and glitches in macOS.
A screenshot is attached. It shows that the shell is running but there is no window.
I am attaching the logs. Something about  `UnhandledPromiseRejectionWarning: Unhandled promise rejection.`
This bug is only in macOS.

**To Reproduce**

1. Copy folder https://github.com/RouR/learn-project/tree/master/electron
2. npm install
3. npm run electron:start

**Expected behavior**
1. A window should appear.
2. The behavior should be the same as in Windows

**Desktop:**
OS: MacOs BigSur 11.1
@capacitor-community/electron: "3.0.1", 
@capacitor/core: "3.1.1", 
web-app created with "@ionic/angular": "6.0.0-dev.202106282030.9f3b1d9"

**Terminal logs**
```
user@mac electron % ls 
app			capacitor.config.json	package-lock.json	tsconfig.json
assets			dist			package.json		user-preload-script.js
build			node_modules		src
user@mac electron % npm install
npm WARN learn-project@1.0.0 No repository field.

audited 449 packages in 11.386s

43 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

user@mac electron % npm run electron:start

> learn-project@1.0.0 electron:start /Users/user/Desktop/electron
> npm run build && electron ./


> learn-project@1.0.0 build /Users/user/Desktop/electron
> tsc

(node:7538) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/user/Desktop/electron/node_modules/@capacitor-community/electron/dist/runtime/electron-plugins.js'
Require stack:
- /Users/user/Desktop/electron/node_modules/@capacitor-community/electron/dist/core/util.js
- /Users/user/Desktop/electron/node_modules/@capacitor-community/electron/dist/core/index.js
- /Users/user/Desktop/electron/build/src/index.js
- /Users/user/Desktop/electron/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.setupCapacitorElectronPlugins (/Users/user/Desktop/electron/node_modules/@capacitor-community/electron/dist/core/util.js:93:21)
    at ElectronCapacitorApp.init (/Users/user/Desktop/electron/build/src/index.js:102:20)
    at /Users/user/Desktop/electron/build/src/index.js:127:26
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:7538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

![2021-07-13 180306](https://user-images.githubusercontent.com/1227355/125481816-3111022f-13ed-47e5-8cb8-22061f909ef9.jpg)

**Comment by RouR** [comment]
I guess the reason is  https://github.com/capacitor-community/electron/blob/4ce5fbc49cda07bccbd6f3941c3a489d574219d2/src/electron/util.ts#L90

File `node_modules/@capacitor-community/electron/dist/runtime/electron-plugins.js'` does not exist

**Comment by RouR** [comment]
Workaround: `npx cap update electron`
https://github.com/capacitor-community/electron/issues/110

but, it must work out-of-box

**Comment by IT-MikeS** [comment]
By your example repo I don't see the web app containing the electron folder.

Normally the flow of creating a project would be to:

1. Create web app project via ionic cli, create react app, vue cli, etc.
2. Add the Capacitor core and cli as shown in the capacitor docs
3. Build the project via npm run build or similar
4. Follow the getting started guide in the [electron platform docs](https://capacitor-community.github.io/electron/#/./getting-started/index)

If I've missed something in your demo repo then please reopen an issue but I can not reproduce this on the same version of macOS when I go through the process above.
