### ISSUE TITLE
Running Platform Sync from `npm run` causes build Failure

### ISSUE THREAD

**Issue by warrenonedge** [capacitor-community/electron#112]
**Describe the bug**
When trying to run `npx cap sync @capacitor-community/electron` from a npm run script (i.e `npm run build:electron` custom script in package.json) causes the build to fail due to inability to find package.json and capacitor.config.json.

**To Reproduce**

1. Add package.json script to sync electron platform
2. npm run <name_of_script>
3. See error in logs

**Expected behavior**
Running npx cap sync @capacitor-community/electron from terminal or from package.json scripts should function exactly the same since the CWD is the project root directory.

**Screenshots**

<img width="1104" alt="Screen Shot 2021-07-13 at 2 15 17 PM" src="https://user-images.githubusercontent.com/1473474/125504445-43f6ce19-26f4-4d61-bb9c-adb182e7b113.png">

**Desktop (please complete the following information):**

- OS: MacOS 
- Version: Big Sur 11.4

**Additional context**
@capacitor-community/electron:^1.4.2
@capacitor/cli:^3.0.0

**Comment by warrenonedge** [comment]
$ node --version && npm --version
v14.17.0
6.14.13

**Comment by warrenonedge** [comment]
I just realized im running an extremely old version of @capacitor-community/electron. will try updating to v3 and respond back.

**Comment by warrenonedge** [comment]
After updating to Version 3.0.1 and now im getting below error. Unable to find electron-plugins.js

I preformed a `npm clean-install` and did a new `ionic build`

<img width="1099" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/1473474/125507139-02af3405-4e5f-497a-9fb6-b17e6871d852.png">

**Comment by IT-MikeS** [comment]
Try running `npx cap update @capacitor-community/electron` then trying your commands again

**Comment by warrenonedge** [comment]
So updating to @capacitor-community/electron@3.0.1 is causing me more issues since It is recommended to remove the entire platform and re-add it. We have a few 'after sync' scripts that run and electron-updater configured that id have to reconfigure. 

I've switched back to @1.4.2 

@IT-MikeS that command works from terminal by itself but for some reason when running it using `npm run` it fails with above errors.

On version 1.4.2 im getting the first screenshot. On version 3.0.1 im getting the second screenshot error.

Going forward I will be staying on 1.4.2 which I know is deprecated. Until such time we can update to V3.0.1+ This is not a blocker for me since i can do it from command line instead of `npm run`

**Comment by warrenonedge** [comment]
I'm going to close this ticket and link it in a new ticket if, after we migrate to v3, the issue persists.

**Comment by IT-MikeS** [comment]
V4 is coming that resolves a few issues and greatly improves the dev experience and the plug-in system

**Comment by warrenonedge** [comment]
Thanks will try to move to that when we can.
