### ISSUE TITLE
Build process broken with Ionic, Angular 12 and Webpack 5

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/electron#117]
**Description**
After adding the @capacitor-community/electron platform the build process `ionic build` does not work anymore.
It throws multiple errors, regarding a breaking change in webpack 5. They removed polyfills for node.js core modules.

**Steps to reproduce the behavior:**

1. Start ionic app with electron platform
```
$ ionic start my-electron-app tabs
$ cd my-electron-app
$ npm i capacitor-community/electron
$ npx cap add @capacitor-community/electron
```

2. Add the following line to the constructor in `app.component.ts` file like this:

```
    console.log(app.getBadgeCount());
```

3. Try to build the app
```
$ ionic build
```

**Expected behavior**
Well, either the build process should work as expected, without any interventions of the developer **-OR-** if any interventions of the developers are necessary, these should be documented on the documentation page of this project.

**Screenshots**
![Bildschirmfoto 2021-07-22 um 18 37 23](https://user-images.githubusercontent.com/1294854/126676388-9c482435-5442-443e-9130-e58d7e2e4d17.png)

**Demo repository:**
https://github.com/tobiasmuecksch/capacitor-electron-error-demo

**Comment by IT-MikeS** [comment]
The issue stems from importing electron into the web app. This issue isn't really the fault of this repo but rather Webpack 5 removing their poly-fills. 

However, you should know that it's not best practice to import electron directly into the web-app portion of an electron application (renderer process). 
You may want to instead utilize the [Context Isolation bridge](https://www.electronjs.org/docs/tutorial/context-isolation) with a pre-load script and expose parts of electron via custom functions to the window object. From that point you can create a service or util that utilizes the window objects you have exposed in the web-app.

Unfortunately there is nothing in this repo/project that I can change to correct this behavior but I hope the above info aids you in resolving the issue.

**Comment by tobiasmuecksch** [comment]
@IT-MikeS Thank you so much for this very helpful in-depth answer.
