### ISSUE TITLE
How to send an event from main to renderer.

### ISSUE THREAD

**Issue by laclance** [capacitor-community/electron#121]
I am trying to do something similar to this http://www.matthiassommer.it/programming/frontend/two-ways-to-react-on-the-electron-close-event/, where I send an event to my app when electron is closing. Seems like it used to be possible with IPC messages but trying to use any electron packages in my app causes `r.existsSync is not a function` error 
from line 8 `  if (fs.existsSync(pathFile))` in `capacitor-electron://-/static/node_modules/electron/index.js` 
and line 9 `const { ipcRenderer } = require("electron");` 
in `electron\node_modules\@capacitor-community\electron\dist\runtime\electron-rt.js`

To reproduce just `npm install electron` and `import { ipcRenderer } from 'electron'`;
Using windows 10 and create-react-app.

**Comment by IT-MikeS** [comment]
What version of the platform are you using?

**Comment by laclance** [comment]
"^3.0.2"

**Comment by laclance** [comment]
I created one https://github.com/laclance/electron-ipc-test

**Comment by IT-MikeS** [comment]
Merge the [PR](https://github.com/laclance/electron-ipc-test/pull/1) I have submitted to your demo repo or clone my [Fork](https://github.com/IT-MikeS/electron-ipc-test) of your repo and run:

1. `yarn`
2. `yarn run build && npx cap copy @capacitor-community/electron && npx cap open @capacitor-community/electron`

To see the demo working, and then you can look around the code to see what I did :+1:  

This is much easier than typing a long message in comments :smile:

**Comment by laclance** [comment]
Thank you so much, I was not able to get the sample app running but used the code to get my main app working.

`electron\src\index.ts`
```
    this.MainWindow.on('close', e => {
      if (this.MainWindow) {
        e.preventDefault();
        this.MainWindow.webContents.send('app-close');
      }
    });
```
`src\App.tsx`
```
    if (Capacitor.getPlatform() === 'electron') {
      const { ipcRenderer } = window.require('electron');
      try {
        ipcRenderer.on('app-close', () => window.alert('closing'));
      } catch (e) {
        window.alert(e.message);
      }
    }

**Comment by IT-MikeS** [comment]
You'll need to use the contextBridge in the preload file to expose single events using ipc. See the following docs: 

https://www.electronjs.org/docs/latest/api/context-bridge
