### ISSUE TITLE
Cannot find module 'electron' or its corresponding type declarations.

### ISSUE THREAD

**Issue by barocsi** [capacitor-community/electron#122]
**Describe the bug**
After step by step doing the getting started page, at step
npx cap open @capacitor-community/electron
result:
../node_modules/@capacitor-community/electron/dist/core/ElectronSplashScreen.d.ts(1,22): error TS2307: Cannot find module 'electron' or its corresponding type declarations.

Something trivial am i missing here?

**Comment by IT-MikeS** [comment]
Could you post a repo containing a project with the issue that I could look at?
