### ISSUE TITLE
Plugin Events

### ISSUE THREAD

**Issue by hampoelz** [capacitor-community/electron#137]
Is there a way to emit my own events like in a web plugin? I haven't found a way to do this. There's also no documentation for this.

**Comment by IT-MikeS** [comment]
I am working on this, hopefully something soon

**Comment by hampoelz** [comment]
Nice to hear, thank you. 👍

**Comment by KoenLav** [comment]
This has been [implemented in 4.1.0](https://github.com/capacitor-community/electron/blob/main/CHANGELOG.md#410-2022-01-22).
