### ISSUE TITLE
Typings are not included in `@capacitor-community/electron`

### ISSUE THREAD

**Issue by itsMapleLeaf** [capacitor-community/electron#148]
**Describe the bug**
The typings are missing in the `@capacitor-community/electron` package.

**To Reproduce**
Set up a project. In the `electron/src/setup.ts` file, the various imports from `"@capacitor-community/electron"` are `any`, and you get this message:
![image](https://user-images.githubusercontent.com/19603573/137429245-900e3545-e7fb-4240-8a53-01fd45948e8f.png)

**Expected behavior**
Should be able to import non-`any` types.

**Screenshots**

Typings point to a missing file:
![image](https://user-images.githubusercontent.com/19603573/137429456-e92f8ccb-7ba7-4aa0-aec4-ecf252475f4b.png)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser N/A
- Version N/A

**Smartphone (please complete the following information):**

- Device: N/A
- OS: N/A
- Browser N/A
- Version N/A

**Additional context**
N/A

**Comment by SatheeshKumarBalu** [comment]
Getting same issue, any update or workaround for this..
![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/34299834/154209472-a35e983d-c0e0-4cad-9c52-79c838f8a89f.png)
![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/34299834/154209482-09c0f7d5-5d32-42fa-a4e1-32fcb8d3ef5e.png)

**Comment by Koulwa** [comment]
any update on this?

**Comment by troywweber7** [comment]
Is this project dead? And if so, what should I be using instead?

**Comment by troywweber7** [comment]
Okay, thanks for the update. If I get an opportunity to contribute I'll do so. I'm just in that phase right now where I'm looking around and finding lots of sparsely related clues about the correct way to proceed. This plugin seems to be the cleanest approach so far, I just got worried for a second when types weren't there.

**Comment by IT-MikeS** [comment]
Fixed ing 4.1.2
