### ISSUE TITLE
Dynamically edit Content-Security-Policy

### ISSUE THREAD

**Issue by laclance** [capacitor-community/electron#150]
Trying to connect to a "random" websocket address but then it seems will need some way of being able to dynamically add the address to the Content-Security-Policy once it is known.

`create-or-join.ts:99 Refused to connect to 'ws://10.0.0.7:8082/' because it violates the following Content Security Policy directive...`

**Comment by laclance** [comment]
yeah because the websocket address is selected by the user.

**Comment by Estevete** [comment]
> You may not be able to do that, or you'll have to remove the CSP. Can't say I know for certain if it's not possible though

How can I remove the CSP? I'm facing the same issue.
