### ISSUE TITLE
Custom made plugins does not seem to survive packaging

### ISSUE THREAD

**Issue by filpet95** [capacitor-community/electron#155]
**Describe the bug**
The automatically generated paths for detected electron plugins are an absolute path to the developers machine. Hence, when packaging the app and installing it on another computer the application will fail, saying not finding the module.

**To Reproduce**

1. Create and build a plugin using the plugin example
2. Import the plugin into an application
3. The plugin is detected and added to the file ' src/rt/electron-plugins.js' with an absolute path (Users/xxx/Project/..../electron/node_modules/my-custom-plugin/electron/dist/plugin.js for mac and C:\\Users\\xxx\\Project\\...\\electron\\node_modules\\my-custom-plugin\\electron\\dist\\plugin.js for windows)
4. The application works on local PC as the absolute path is OK. 
5. When packaging the application and running on another PC it yields the following error:
Error: Cannot find module 'C:/Users/xxx/Project/.../electron/node_modules/my-custom-plugin/electron/dist/plugin.js'
Require stack:
- C:/Users/OtherUser/AppData/Local/Programs/Project/resources/app.asar/build/src/rt/electron-plugins.js
- C:/Users/OtherUser/AppData/Local/Programs/Project/resources/app.asar/node_modules/@capacitor-community/electron/dist/core/index.js
- C:/Users/OtherUser/AppData/Local/Programs/Project/resources/app.asar/build/src/index.js
- 
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (- C:/Users/OtherUser/AppData/Local/Programs/Project/resources/app.asar/build/src/rt/electron-plugins.js:2:34)

**Expected behavior**
A relative path to properly detect the plugin. 
For windows '.\\..\\..\\..\\node_modules\\my-custom-plugin\\electron\\dist\\plugin.js' worked. Does not seem to work on mac.

**Desktop (please complete the following information):**

- OS: [Windows, mac]

**Additional context**
electron-builder was used to package the application.

**Comment by jdgjsag67251** [comment]
This should have been fixed in #151

**Comment by IT-MikeS** [comment]
This hasn't been released yet to npm, however except more development of the platform soon. 

I had a bit of a hiatus but will be looking to do more shortly again 👍
