### ISSUE TITLE
ionic electron Error blob

### ISSUE THREAD

**Issue by salemdomain** [capacitor-community/electron#160]
hi, 

Does anyone know what the cause of this error?

Refused to connect to 'blob:capacitor-electron://-/72d107ae-1e8b-49c0-82b5-4462b629eaa9' because it violates the following Content Security Policy directive: "default-src capacitor-electron://* 'unsafe-inline' devtools://* 'unsafe-eval' data:". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
zone.js:1523 Refused to connect to 'blob:capacitor-electron://-/72d107ae-1e8b-49c0-82b5-4462b629eaa9' because it violates the document's Content Security Policy.

am trying to upload image and converting the blob to base64 for live reviewing the image, but i get the above error after selecting the image, i have tried to add <meta but no luck, can anyone help?

**Comment by jdgjsag67251** [comment]
The `blob:` source is not added to the CSP by default. You could add it manually in the `setupContentSecurityPolicy` function

**Comment by IT-MikeS** [comment]
@jdgjsag67251 Is correct
