### ISSUE TITLE
Create DMG for Mac

### ISSUE THREAD

**Issue by justinmoon** [capacitor-community/electron#162]
When I run `npm run electron:pack` in the `electron` directory that's created when I add this `@capacitor-community/electron` to my project, `electron/dist/mac-arm64/<my-app-name>.app` is created  and runs when if I click on it in Finder.

How would I create a `.dmg` installer which would allow user to copy the app into their `Applications` folder which is the standard flow on MacOS?

**Comment by jdgjsag67251** [comment]
In this case you would need to use `npm run electron:make`. This should create a `.dmg` file.
`npm run electron:pack` only builds the app but does not create platform packages.

**Comment by justinmoon** [comment]
OK thanks!
