### ISSUE TITLE
NPM  (including all the merge PR) release missing since more than 5 months

### ISSUE THREAD

**Issue by jepiqueau** [capacitor-community/electron#169]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
To have this plugin maintained, lot of important PRs have been published but no `npm realease` has been published which make all this PR's useless. 
If this plugin is not maintained anymore it must be clearly state so i can remove from my plugins the electron part to avoid receiving issues that i cannot solved myself.

**Describe alternatives you've considered**
There are no alternatives

**Additional context**

**Comment by IT-MikeS** [comment]
My life has been busy so I haven't been doing as much maintenance as I would like, one more PR needs to be resolved and then a new minor release will be published. 

I am also about to start 5.0 development which will bring a lot with it. So most of my upcoming efforts will be there and 4.X will only receive critical fixes, and PRs from others that aren't breaking changes.

This project is definitely not abandoned and I appreciate everyone's patience over the last stretch of time while I sorted out some life stuff. Now with my new job, I'm in a much better place and I'll be back at it very soon!

**Comment by jepiqueau** [comment]
@IT-MikeS Thanks for your answer. I put some messages on slack but you did not answer so i was wondering what is going on. this is why i post this issue, to have some news. If i understand, you are not working anymore for Ionic ? I which you all the best for you new job and hope that you will have enough time for developing 5.0. Your work is greatly appreciate and a lot of developers seems to keep working with electron.

**Comment by IT-MikeS** [comment]
Nope I am indeed working with Ionic since November, I was speaking toward previous 😋

**Comment by jepiqueau** [comment]
@IT-MikeS i am happy of this. That is great for you and you deserve it in view of your hard work since then. 🙏👏👏
