### ISSUE TITLE
How to add media-src directive to the CSP

### ISSUE THREAD

**Issue by jepiqueau** [capacitor-community/electron#206]
**Describe the bug**
I could not find the way in the documentation to add a media-src directive to the content security policy
it is not a bug but a lack of documentation

Can we use the `customUrlScheme` in the ElectronConfig? and if yes how to define the string with the urls of the video
Do we have to change the `setupContentSecurityPolicy` method in the `setup.ts` file  to define a media-src ? if yes how

Thanks 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] ELECTRON

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JuliusSkrisa** [comment]
@jepiqueau if you are using latest version then there is a 'setupContentSecurityPolicy' function in setup.ts file (electron folder). where you can edit CSP string.

**Comment by jepiqueau** [comment]
@JuliusSkrisa thanks for your answer but hiw do i have to edit it let says for example for https:://example.com/example.mp4

**Comment by JuliusSkrisa** [comment]
you should be able to find your answer here https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP but example 2 in the link I think would work.

**Comment by jepiqueau** [comment]
@JuliusSkrisa if finally got it
```
        'Content-Security-Policy': [
          electronIsDev
            ? `default-src ${customScheme}://* 'unsafe-inline' devtools://* 'unsafe-eval' data:; media-src ${customScheme}: https://*`
            : `default-src ${customScheme}://* 'unsafe-inline' data:`,
        ],
```
