### ISSUE TITLE
Not able to add electron platform

### ISSUE THREAD

**Issue by Saqib92** [capacitor-community/electron#228]
**Describe the bug**
Not able to add electron platform in ionic + Capacitor project. 
My project is working absolutely fine with Android / IOS and Web. 

## Error
Running add command throwing this error.
```
$ npx cap add @capacitor-community/electron
ℹ Adding Electron platform: start 🚀
ℹ Adding Electron platform: extracting template
ℹ Adding Electron platform: copying capacitor config file
ℹ Adding Electron platform: setting up electron project
✖ Adding Electron platform: 
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "/bin/sh: line 0: cd: /Volumes/Seagate: No such file or directory
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

```

**To Reproduce**
Just create blank ionic + Capacitor project and Run : `npm i @capacitor-community/electron`

**Expected behavior**
It should add electron platform easily. 

**Screenshots**
![Screenshot 2022-12-23 at 8 18 50 PM](https://user-images.githubusercontent.com/7135885/209358879-08498de2-5908-4196-9fa2-0db0cbd19258.png)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Electron

**Additional context**
Application is working fine with Android and iOS.

**Comment by Saqib92** [comment]
any Update?

**Comment by IT-MikeS** [comment]
Please provide a reproduction repo of your issue with a minimal code base. I could not reproduce this issue on either of my Macs nor a Windows machine using your description.

**Comment by Saqib92** [comment]
Was able to add platform.
Issue was my project is in my extended (external) drive. When i copied my project to main HD the add command works. 
Thanks.

**Comment by dominicwa** [comment]
I think this issue remains and that it fails like this if there's a space in the path to the project.

**Comment by Saqib92** [comment]
> I think this issue remains and that it fails like this if there's a space in the path to the project.

that might be the issue. as my external drive have space between its name.
