### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by tobiasmuecksch** [capacitor-community/electron#247]
As far as I can tell, this project looks pretty abandoned.

1. No real code work since June 2022 (nearly a year)
2. No answers to issues by official maintainers
     - especially no response to outdated electron https://github.com/capacitor-community/electron/issues/233 rings my alarm bells

If this project really is abandoned, please add a corresponding warning to the readme and the documentation.

**Comment by IT-MikeS** [comment]
Thank you for your question and your interest in the Electron Platform for Capacitor. I appreciate your patience and understanding as I navigate through a busy period of my life. 

Firstly, I would like to assure you that the platform is not abandoned. Despite the apparent lack of recent work, the project is very much alive and remains a subject of my attention and commitment. The challenge lies in balancing the demands of my personal and professional life with the time and energy required to maintain and enhance a project like this one.

The platform is a labor of love, provided to the community for free and will always stay that way. This means that finding time to work on it can sometimes be challenging amidst my other commitments. However, I want to reassure you that this doesn't diminish the importance I place on this project nor the value I see in its continued development.

In terms of the future, I'm planning significant updates. The next one will involve a major cleanup of the tooling structure and an overhaul of the overall architecture of the project. This is a substantial task and I'm committed to ensuring it's done correctly, which can take time.

I deeply apologize if my slower pace of work has caused any concern or inconvenience. The community’s enthusiasm for the platform is a driving force behind my commitment to it. I genuinely appreciate your support and understanding, and I promise to continue striving to make this platform the best it can be. 

Thank you again for your support!

**Comment by schwenkreis** [comment]
Hi Mike, 

 

Thanks a lot for the great work and the huge amount of time that you spend on this project. I have benefited a lot in the past from your work and I highly appreciate any further development.

 

Cheers

Friedemann

 

--

Prof. Dr. Friedemann Schwenkreis

Professor für Wirtschaftsinformatik

 

Duale Hochschule Baden-Württemberg

Baden-Wuerttemberg Cooperative State University

Stuttgart

Paulinenstr. 50

70178 Stuttgart 

Tel: +49 711 1849 - 551

Fax: +49 711 1849 - 564

Mob: +49 173 2377266

E-Mail:  ***@***.***> ***@***.***   

 <http://www.dhbw-stuttgart.de/> http://www.dhbw-stuttgart.de

 

-- Your value cannot be expressed in any currency --

 

Von: Mike Summerfeldt ***@***.***> 
Gesendet: Freitag, 12. Mai 2023 04:01
An: capacitor-community/electron ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [capacitor-community/electron] Is this project abandoned? (Issue #247)

 

Thank you for your question and your interest in the Electron Platform for Capacitor. I appreciate your patience and understanding as I navigate through a busy period of my life.

Firstly, I would like to assure you that the platform is not abandoned. Despite the apparent lack of recent work, the project is very much alive and remains a subject of my attention and commitment. The challenge lies in balancing the demands of my personal and professional life with the time and energy required to maintain and enhance a project like this one.

The platform is a labor of love, provided to the community for free and will always stay that way. This means that finding time to work on it can sometimes be challenging amidst my other commitments. However, I want to reassure you that this doesn't diminish the importance I place on this project nor the value I see in its continued development.

In terms of the future, I'm planning significant updates. The next one will involve a major cleanup of the tooling structure and an overhaul of the overall architecture of the project. This is a substantial task and I'm committed to ensuring it's done correctly, which can take time.

I deeply apologize if my slower pace of work has caused any concern or inconvenience. The community’s enthusiasm for the platform is a driving force behind my commitment to it. I genuinely appreciate your support and understanding, and I promise to continue striving to make this platform the best it can be.

Thank you again for your support!

**Comment by tobiasmuecksch** [comment]
Hi @IT-MikeS,
thank you so much for your in-depth response. I highly appreciate your work and this project. 
Since this project obviously is not abandoned, I'm closing this issue accordingly.
