### ISSUE TITLE
Lack of documentation for release 5.0.1

### ISSUE THREAD

**Issue by jepiqueau** [capacitor-community/electron#267]
**Describe the bug**
What are the main changes between v4 and V5, they must be explained
- for an application
- for a plugin

i am the developer of @capacitor-community/sqlite and it was working nicely in v4 and not in v5
in the  [angular-sqlite-app-starter](https://github.com/jepiqueau/angular-sqlite-app-starter) 
- i remove the electron part of the application
- npm uninstall --save @capacitor-community/electron  so it remove the version 4.1.2
- npm i --save @capacitor-community/electron. install 5.0.1
- ng build
- npx cap add @capacitor-community/electron
- cd electron
- remove the nodes_modules and the package-lock.json
- modify the package 
```
  "dependencies": {
    "@capacitor-community/electron": "^5.0.0",
    "@capacitor-community/sqlite": "^5.2.5",
    "better-sqlite3-multiple-ciphers": "^8.4.0",
    "chokidar": "~3.5.3",
    "crypto": "^1.0.1",
    "crypto-js": "^4.1.1",
    "electron-is-dev": "~2.0.0",
    "electron-json-storage": "^4.6.0",
    "electron-serve": "~1.1.0",
    "electron-unhandled": "~4.0.1",
    "electron-updater": "^5.3.0",
    "electron-window-state": "^5.0.3",
    "jszip": "^3.10.1",
    "node-fetch": "2.6.7"
  },
  "devDependencies": {
    "@types/better-sqlite3": "^7.6.4",
    "@types/crypto-js": "^4.1.1",
    "@types/electron-json-storage": "^4.5.0",
    "electron": "^26.2.2",
    "electron-builder": "~23.6.0",
    "electron-rebuild": "^3.2.9",
    "typescript": "^5.0.4"
  },
``` 
- npm install
- cd ..
- npx cap sync @capacitor-community/electron
- ng build
- npx cap copy
- npx cap copy @capacitor-community/electron
- cd electron
- npm run electron:start
- i got 

```
 angular-sqlite-app-starter@1.0.0 build
> tsc && electron-rebuild

node_modules/builder-util-runtime/out/httpExecutor.d.ts:9:5 - error TS2411: Property ''accept-charset'' of type 'string | string[]' is not assignable to 'string' index type 'string'.

9     [key: string]: string;
      ~~~~~~~~~~~~~~~~~~~~~~
...

Found 16 errors in the same file, starting at: node_modules/builder-util-runtime/out/httpExecutor.d.ts:9
``` 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mtpc** [comment]
FYI, this is fixed by adding `"skipLibCheck": true` in the tsconfig.json that's inside the electron folder

**Comment by jepiqueau** [comment]
@mtpc thanks for the fix

**Comment by gpetrov** [comment]
this is also fixed by just updating the dev dependencies of electron-updater to v6 and electron-builder to v24
@IT-MikeS  can you update those on the default template?
