### ISSUE TITLE
Unable to add Electron to existing Capacitor project

### ISSUE THREAD

**Issue by coreyjv** [capacitor-community/electron#34]
**Describe the bug**

I receive the following error when adding `@capacitor-community/electron`:

```
$ npx cap add @capacitor-community/electron
[error] Invalid platform: "@capacitor-community/electron". Valid platforms include: android, electron, ios, web
```

**To Reproduce**

Followed the installation instructions in the `README`

**Expected behavior**

Community version of electron should be installed and able to be used.

**Additional context**

Relevant versions of dependencies in project:

```
    "@capacitor-community/electron": "^0.5.4",
    "@capacitor/android": "^2.3.0",
    "@capacitor/core": "^2.3.0",
    "@capacitor/ios": "^2.3.0",
    "@ionic-enterprise/auth": "^3.1.1",
    "@ionic-native/core": "^5.27.0",
    "@ionic/react": "^5.2.3",
```

**Comment by IT-MikeS** [comment]
It sounds like you have and old version of the `@capacitor/cli` have you cleared your `node_modules` folder and tried to reinstall your dependencies?

**Comment by coreyjv** [comment]
@IT-MikeS -- The `@capacitor/cli` isn't installed as far as I know when spinning up a project based on a template from the Ionic team. Are you suggesting I install it within the project and then run the command in the docs?

**Comment by coreyjv** [comment]
I missed that in my `package.json` and once I updated `@capacitor/cli` to the latest I was able to add the platform. Thanks for pointing that out!

**Comment by IT-MikeS** [comment]
Glad to hear its working 👍
