### ISSUE TITLE
Expose Electron builder configuration properties via capacitor.config.json and change build process to read them dynamically

### ISSUE THREAD

**Issue by coreyjv** [capacitor-community/electron#42]
In doing some testing on deep linking in #36 I realized that the built app was pulling _statically defined_ properties from the `electron/package.json` which is mentioned in the [Quick Setup](https://www.electron.build/#quick-setup-guide) guide for Electron Builder.

I would like to see these values pulled dynamically from the `capacitor.config.json` at the root of the project. 

So the mapping would be as follows:

Capacitor Property | Electron Builder Property
------------ | -------------
`appId` | `appId`
`appName` | `productName`

There's likely additional properties we'd want to expose as well like Electron Builder's `mac.category.`

Finally I believe for deep linking to work for built application it has to be _statically defined_ per the discussion here: https://github.com/electron-userland/electron-builder/issues/1552 so I think it's worth exposing the custom protocol or scheme in the configuration and not have to modify the `electron.index.ts` to set it.

**Comment by IT-MikeS** [comment]
Yep most static configuration options will be in the capacitor.config come version 3 of capacitor. See https://github.com/ionic-team/capacitor/issues/3141

Like the Android and iOS platforms of Capacitor, Electron will still follow the idea of not getting in the way of the normal development of that platform. So if a process is done one way in electron apps without capacitor, I don't want to make it different in the capacitor platform.

**Comment by IT-MikeS** [comment]
This will be in v3

**Comment by coreyjv** [comment]
@IT-MikeS -- What does the solution for this look like? I wouldn't mind contributing to the feature but would like to understand what you're looking for.

Thanks!
