### ISSUE TITLE
The electron platform is deprecated

### ISSUE THREAD

**Issue by JoaoEdu93** [capacitor-community/electron#49]
Hi!

I have an Ionic app and now I was deploying to Windows using Electron.
When I ran the command `npx cap add electron` I received the warning **The electron platform is deprecated!**
What is the reason for this warning? Is there a better alternative?

**Comment by tobiasmuecksch** [comment]
Hi @JoaoEdu93,

`npx cap add electron` is deprecated. Instead please refer to the documentation of the community version of the electron platform.

See: https://capacitor-community-electron-docs-site.vercel.app/getting-started

**Comment by edocbuhtig** [comment]
Anyone looking for a solution for "deprecation warning of electron" and switching to the community version see the [steps here](https://www.youtube.com/watch?v=vxKZo5dFzI8&feature=youtu.be)
