### ISSUE TITLE
Livereload for Ionic React app

### ISSUE THREAD

**Issue by Arxi** [capacitor-community/electron#50]
Is the livereload for this electron platform currently possible?

I have an Ionic React app. I'm trying calling this command from project root folder:
 `ionic cap run @capacitor-community/electron -l`

It first tries to add the electron platform again:
 ` capacitor add @capacitor-community/electron`
 which fails with `Error: Electron platform already exists.` but continues with build process, so in my case these steps:

 `react-scripts start`
 `capacitor copy @capacitor-community/electron`
 `capacitor open @capacitor-community/electron`

So in the end, it opens the electron window, but the content displayed is outdated - actually an old build I made in the past by manually doing 
 `ionic build && npx cap copy`
The content is not live-reloaded.

Am I doing something wrong or livereload is not available for electron?

Thank you!

**Comment by IT-MikeS** [comment]
Currently no, live reload does not work with electron, but its a good idea for a future release. 👍

**Comment by digaus** [comment]
Livereload would be really nice feature :)

**Comment by teddykishi** [comment]
I don't know if it helps, but I'm using Ionic with Angular and I used [electron-reload](https://www.npmjs.com/package/electron-reload)"  
I added those lines in electron/src/index.ts
```require('electron-reload')(__dirname, {
  electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
});
```
and live reloading is now working

**Comment by IT-MikeS** [comment]
> I don't know if it helps, but I'm using Ionic with Angular and I used [electron-reload](https://www.npmjs.com/package/electron-reload)"
> I added those lines in electron/src/index.ts
> 
> ```
>   electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });
> ```
> 
> and live reloading is now working

This is a good option, I'd still like to build something into the platform, but keep an eye out for v3 it will have some good updates for everyone

**Comment by gaurav-vachhani** [comment]
> I don't know if it helps, but I'm using Ionic with Angular and I used [electron-reload](https://www.npmjs.com/package/electron-reload)"
> I added those lines in electron/src/index.ts
> 
> ```
>   electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });
> ```
> 
> and live reloading is now working

Can you please share more details on build commands?

**Comment by IT-MikeS** [comment]
Added in v4 (v3 will be deprecated), you will need to build your app then run `npx cap copy @capacitor-community/electron` to see the reload.

**Comment by polisettyManoj** [comment]
> I don't know if it helps, but I'm using Ionic with Angular and I used [electron-reload](https://www.npmjs.com/package/electron-reload)" I added those lines in electron/src/index.ts
> 
> ```
>   electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });
> ```
> 
> and live reloading is now working

Can you give me the steps for live reload ??

**Comment by justinmoon** [comment]
If your web dev build has live-reload (e.g. `create-react-app`) and you do [this](https://github.com/capacitor-community/electron/issues/120#issuecomment-916246763) then your electron dev build will too.

**Comment by polisettyManoj** [comment]
> I don't know if it helps, but I'm using Ionic with Angular and I used [electron-reload](https://www.npmjs.com/package/electron-reload)" I added those lines in electron/src/index.ts
> 
> ```
>   electron: path.join(__dirname, 'node_modules', '.bin', 'electron')
> });
> ```
> 
> and live reloading is now working

can you share with me more details and steps to live-reload ?
I'm using ionic + angular with "@capacitor-community/electron": "^4.0.1"
