### ISSUE TITLE
Getting started Guide: How to start?

### ISSUE THREAD

**Issue by AndrewBedscastle** [capacitor-community/electron#52]
**Describe the bug**
Following the guide
https://capacitor-community-electron-docs-site.vercel.app/getting-started
It says use the script `electron:start`
I don't know how do that? in the electron folder there is no script like that
I also tried every combination with npx cap without luck

How can I even start it?

**To Reproduce**
Following all steps in https://capacitor-community-electron-docs-site.vercel.app/getting-started

Dependencies

"dependencies": {
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@capacitor-community/electron": "^1.2.3",
    "@capacitor/core": "2.4.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.3.0",
    "electron": "^9.2.1",
    "ngx-electron": "^2.2.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },

**Expected behavior**
Electron starting as with the old way `npx cap open electron`

**Desktop (please complete the following information):**

- OS: Windows 10 x64
- Browser Firefox, but irrelevant as it does not open
- Version 79.0

**Comment by IT-MikeS** [comment]
`npx cap open electron` should function with the community version from your web app directory.

**Comment by AndrewBedscastle** [comment]
Seems as if it then starts the old version

npx cap open electron
**[warn] The electron platform is deprecated!**

How's that electron:start script supposed to be used mentioned in the getting started guide?
It's a bit frustrating if the "hello world example does not work"

**Comment by BartokW** [comment]
> npx cap open electron

This should work
`npx cap open @capacitor-community/electron`

> How's that electron:start script supposed to be used mentioned in the getting started guide?
> It's a bit frustrating if the "hello world example" does not work

If you cd into the electron folder then the electron start script will work 
`npm run electron:start`

**Comment by AndrewBedscastle** [comment]
Thank you!
Would you please add that to the quick start guide?

I can confirm both works!

**Comment by IT-MikeS** [comment]
New github pages docs reflects these changes
