### ISSUE TITLE
Setting environment variables

### ISSUE THREAD

**Issue by aleksei-tro** [capacitor-community/electron#55]
I'm trying to work out how to set the GOOGLE_API_KEY as per instructions here
[https://github.com/electron/electron/blob/master/docs/api/environment-variables.md](https://github.com/electron/electron/blob/master/docs/api/environment-variables.md)
but I'm not sure what it's referring to, here:
> main process file, before opening any browser windows that will make geolocation requests

**Comment by IT-MikeS** [comment]
In your `*yourAppDir*/electron/src/index.ts` add the line `process.env.GOOGLE_API_KEY = 'YOUR_KEY_HERE';` to the top of the file, after the import statements. This is what that article is explaining. 

The better option is to make it set from either a small proxy server or other off client way of making requests so people cant find and use your key if the software is made public.

**Comment by enso-media** [comment]
Having the same problem here and the described instructions dont work. Electron forces the use of the GOOGLE_API_KEY environment variable, however its not possible to set this variable, as an React App build with Capacitor only allows environment variables starting with REACT_APP_ (see: https://create-react-app.dev/docs/adding-custom-environment-variables/). So if you set the correct variable, it gets stripped away by React even on Runtime.
