### ISSUE TITLE
electron.exe seems to be included twice

### ISSUE THREAD

**Issue by vespasianvs** [capacitor-community/electron#56]
**Describe the bug**
I have just moved onto capacitor-community/electron after using capacitor/electron for quite a while. I noticed that my finished exe files generated after switching were twice the size as the exe files produced by capacitor/electron. Upon some investigation it appears as though in win-unpacked I have the exe file (renamed to match my exe name) in the root of win-unpacked but I *also* have it in "win-unpacked\resources\app.asar.unpacked\node_modules\electron\dist\electron.exe". At 108MB, I'm guessing this is the problem. I guess this *could* be a problem with electron-builder config or something, but it's worked fine so far with capacitor/electron so if there are some changes I need to make to the config for community-capacitor then I really need to know.

**To Reproduce**

1. Take a project that has been using capacitor/electron.
2. Remove the capacitor/electron platform and setup capacitor-community/electron as per the instructions on the website.
3. Build the app and npx cap copy
4. Run npm run electron:build-windows

**Expected behavior**
I would expect the exe file to be a similar size as to when I was using capacitor/electron - not twice the size. If there is a config change needed, I'd expect some sort of instruction on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/56588504/92898641-119a3c80-f416-11ea-94d7-1e26d0f5ce8c.png)
![image](https://user-images.githubusercontent.com/56588504/92898933-4c9c7000-f416-11ea-96f4-436fa8912b69.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Edge
- Version: 85

**Comment by vespasianvs** [comment]
For completeness, here is an anonymised chunk of my package.json from the electron folder:

`"main": "./build/index.js",
	"scripts": {
		"build": "tsc",
		"electron:start": "npm run build && electron ./",
		"electron:pack": "npm run build && electron-builder build --dir",
		"electron:build:mac": "NOTARIZE=disable electron-builder build --mac",
		"electron:build:win": "NOTARIZE=disable electron-builder build --windows",
		"electron:sign:win": "npm run build && electron-builder build --windows",
		"electron:sign:mac": "npm run build && electron-builder build --mac"
	},
	"dependencies": {
		"@capacitor-community/electron-core": "file:capacitor-community-electron-core-1.2.3.tgz",
		"electron-log": "^4.2.4",
		"electron-notarize": "^1.0.0",
		"electron-updater": "^4.3.4"
	},
	"devDependencies": {
		"electron": "^9.1.1",
		"electron-builder": "^22.7.0",
		"typescript": "~3.9.5"
	},
	"keywords": [
		"capacitor",
		"electron"
	],
	"build": {
		"generateUpdatesFilesForAllChannels": true,
		"directories": {
			"buildResources": "assets"
		},
		"asar": true,
		"publish": {
			"provider": "*****",
			"name": "*****",
			"region": "*****",
			"path": "*****"
		},
		"mac": {
			"hardenedRuntime": true,
			"gatekeeperAssess": false,
			"entitlements": "./*****",
			"entitlementsInherit": "./*****"
		},
		"win": {
			"target": "nsis",
			"sign": "./*****"
		},
		"nsis": {
			"oneClick": false,
			"perMachine": false,
			"allowElevation": true,
			"allowToChangeInstallationDirectory": true,
			"deleteAppDataOnUninstall": true,
			"include": "./build/installer.nsh"
		},
		"protocols": {
			"name": "*****-deep-link",
			"schemes": [
				"*****"
			]
		},
		"afterSign": "./*****"
	}`

You will note I am using a custom version of capacitor-community/electron (a PR will follow once I have finished testing!), but it does the same thing when using the current latest version from the main repo too.

**Comment by vespasianvs** [comment]
Currently getting round the unpacked additional inclusion of electron by adding the following to the 'files' config option for electron-builder:

"!**/node_modules/electron${/*}"

The build works fine and I don't have electron included twice

**Comment by IT-MikeS** [comment]
I'll take a look this weekend, it's most likely an oversight with default build config

**Comment by vespasianvs** [comment]
@IT-MikeS Did you have any luck with this?

**Comment by IT-MikeS** [comment]
Sorry for the delay, this had to do with where `electron` was listed as a dep, it should be a peerDep, this will be fixed next release!

**Comment by IT-MikeS** [comment]
Fixed in `v1.3.0`
