### ISSUE TITLE
Set Window Size

### ISSUE THREAD

**Issue by johnwargo** [capacitor-community/electron#57]
How do you set the window size for the Electron `BrowserWindow`?

It feels like I should be able to do this using the config object passed to `myCapacitorApp.init();` but I don't see anything like that in the docs.

**Comment by coreyjv** [comment]
Have you tried setting the `windowOptions` as noted here?

https://github.com/capacitor-community/electron/blob/main/packages/core/src/electron/interfaces.ts#L43

**Comment by johnwargo** [comment]
@coreyjv no, I haven't, but the docs there say that's for the splash screen, I want to set the browserwindow size.

**Comment by coreyjv** [comment]
Splash screen options are set with a different key: https://github.com/capacitor-community/electron/blob/main/packages/core/src/electron/interfaces.ts#L23

**Comment by johnwargo** [comment]
oops, sorry - didn't see that. Will look into it, thanks.

**Comment by johnwargo** [comment]
I documented the solution here: https://randomerrors.dev/2020/09/24/ionic-capacitor-configuration

**Comment by fromage9747** [comment]
@johnwargo mainWindow does not exist on createCapacitorElectronApp().  Can't for the life of me set the browser window or custom icons...

**Comment by johnwargo** [comment]
I see that the article URL changed, here's the current version: https://randomerrors.dev/posts/2020/ionic-capacitor-configuration/

@fromage9747 yeah, that solution was three years ago, things have likely changed.
