### ISSUE TITLE
Cannot find module './server'

### ISSUE THREAD

**Issue by aqilusman45** [capacitor-community/electron#59]
**Describe the bug**
I have created a separate module that is an express server which is being started in the main i.e index.js file. The issue is that the imported module works fine when I do `npm run electron:start` and the server listens but when I build it throws an exeption saying `Cannot find module './server'`.

**To Reproduce**

1. Initialize a new capacitor project.
2. Add electron using these [steps](https://capacitor-community-electron-docs-site.vercel.app/getting-started)
3. Add a module in the `./src` and import it in` index.js`file.
4. Create build and run the app.

**Expected behavior**
Compiled code from ./build folder should all go to production build.

**Screenshots**
production:
![image](https://user-images.githubusercontent.com/46997126/93671644-25047200-fabe-11ea-9976-2a61ac0b8d1d.png)
electron:start
![image](https://user-images.githubusercontent.com/46997126/93671662-4f562f80-fabe-11ea-9f7a-302d893266ee.png)

**Desktop (please complete the following information):**

- OS: Windows 10 
- Browser: Chrome
- Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**
By the way the app and server works find if I do everything in one file.

**Comment by IT-MikeS** [comment]
Do you have an example repo of this issue?

**Comment by IT-MikeS** [comment]
Fixed with, 39a8e4b62d71d189b77d8d09ec4ee2626fd15939

This will be in 1.3.1

**Comment by LuizTokuhara** [comment]
> **Describe the bug**
> I have created a separate module that is an express server which is being started in the main i.e index.js file. The issue is that the imported module works fine when I do `npm run electron:start` and the server listens but when I build it throws an exeption saying `Cannot find module './server'`.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Initialize a new capacitor project.
> 2. Add electron using these [steps](https://capacitor-community-electron-docs-site.vercel.app/getting-started)
> 3. Add a module in the `./src` and import it in` index.js`file.
> 4. Create build and run the app.
> 
> **Expected behavior**
> Compiled code from ./build folder should all go to production build.
> 
> **Screenshots**
> production:
> ![image](https://user-images.githubusercontent.com/46997126/93671644-25047200-fabe-11ea-9976-2a61ac0b8d1d.png)
> electron:start
> ![image](https://user-images.githubusercontent.com/46997126/93671662-4f562f80-fabe-11ea-9f7a-302d893266ee.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Windows 10
> * Browser: Chrome
> * Version 85.0.4183.102 (Official Build) (64-bit)
> 
> **Additional context**
> By the way the app and server works find if I do everything in one file.

Hi did you found a solution for it?
I am having the same problem, it works on electron:start but not after production build.
It is not finding the express server.

**Comment by IT-MikeS** [comment]
> Fixed with, 39a8e4b62d71d189b77d8d09ec4ee2626fd15939
> 
> This will be in 1.3.1

@LuizTokuhara please see the above, please make sure you are using the latest version of the electron platform

**Comment by LuizTokuhara** [comment]
> > Fixed with, [39a8e4b](https://github.com/capacitor-community/electron/commit/39a8e4b62d71d189b77d8d09ec4ee2626fd15939)
> > This will be in 1.3.1
> 
> @LuizTokuhara please see the above, please make sure you are using the latest version of the electron platform

Hi IT-MikeS, thanks for your reply.
Actually on my project, electron is not finding the express module, but it is included in node_modules (root and electron).
Don't know why it is happening.
![Screen Shot 2020-12-12 at 13 04 33](https://user-images.githubusercontent.com/26283844/101988823-f9d38e00-3c7a-11eb-85d9-2fd841092867.png)
