### ISSUE TITLE
Contribute to docs

### ISSUE THREAD

**Issue by johnwargo** [capacitor-community/electron#60]
I want to contribute to the docs for this project, how do I do that?

I asked a question a few weeks ago about setting window properties and now that I have the answer, I want to add it to the docs. 

https://randomerrors.dev/2020/09/24/ionic-capacitor-configuration

**Comment by johnwargo** [comment]
Please?

**Comment by johnwargo** [comment]
Pretty please?

**Comment by deploystudios** [comment]
can @johnwargo please contribute to the docs for this? I saw the official release of ionic Vue and it says: "Target iOS / Android / Electron / PWA" but there is no info to be found on how to use Electron with ionic (at least none that I can find)

**Comment by IT-MikeS** [comment]
> can @johnwargo please contribute to the docs for this? I saw the official release of ionic Vue and it says: "Target iOS / Android / Electron / PWA" but there is no info to be found on how to use Electron with ionic (at least none that I can find)

You dont use electron directly with ionic, you use ionic with capacitor, and capacitor uses electron/android/ios.

once you have capacitor added to your ionic project follow the steps outlined here: https://capacitor-community-electron-docs-site.vercel.app/getting-started to use electron
