### ISSUE TITLE
CORS issue for capacitor electron

### ISSUE THREAD

**Issue by xfranklin501** [capacitor-community/electron#61]
Hi Team,

Is there a way where we can customize the host url for electron app which we develop through capacitor.

The config in the below link speaks only about android & iOS

[https://capacitorjs.com/docs/reference/config](https://capacitorjs.com/docs/reference/config)

![image](https://user-images.githubusercontent.com/3923644/94432966-35e76e80-01b5-11eb-87c1-b8e0d5a3dad1.png)

Currently the origin is capacitor-electron:// and not able to modify it.

Thank you,
Frank

**Comment by IT-MikeS** [comment]
What is it you need it to be different for?

**Comment by digaus** [comment]
@xfranklin501 

If you have CORS issues you can just disable it with

`app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');`

See https://github.com/electron/electron/issues/23664#issuecomment-631674094

**Comment by challamzinniagroup** [comment]
@digaus I am experiencing CORS issues, the above line you reference is created for me in the build/index.js file - but seems to have no effect.

**Comment by IT-MikeS** [comment]
Do you have an example of the use case? I've built many apps in electron, both for work and side job clients, and even repaired a few apps for them and the only cors issues I've ever came across were symptoms of a design issues or a case of trying to "shoehorn" something, so I'm interested in what the use case is.

**Comment by challamzinniagroup** [comment]
@IT-MikeS Thanks for following up. I'm not entirely sure what all information to offer - here goes (just let me know what else you need. Thanks!)

- I have recently begun building an Angular/Ionic/Capacitor/Electron and had no issues other than the deprecation warning (referenced in https://github.com/capacitor-community/electron/issues/49).
- Following the link provided in that issue (https://capacitor-community-electron-docs-site.vercel.app/getting-started/), I removed the electron folder, ran the said commands, and opened the app, now under the cap-community.
- The DevTools console displays the following error when I attempt to sign in (which triggers the app's first outside http call.
![image](https://user-images.githubusercontent.com/39888692/97043515-9a8db300-1540-11eb-8c5e-ddc86da282f4.png)

Nothing in the angular/ionic code changed between the original electron and the cap-community electron. Also, nothing was done to the electron folder after the `npx cap add ...` command was executed - this is a completely default cap-community electron folder, only with the `npx cap copy` and `npx cap open @capacitor-community/electron` commands executed.

**Comment by IT-MikeS** [comment]
Can I ask where your call is being made to? Is it like a hosted service or an server you own and operate?

**Comment by challamzinniagroup** [comment]
The call is going out to an API that is hosted in a controlled VM.

I remembered having to add the `webSecurity: false` in the prior electron (non cap-community) but was unsure of how to do it here. Following your suggestion, I added this:

```
const myCapacitorApp = createCapacitorElectronApp({
  mainWindow: {
    windowOptions: {
      webPreferences: {
        webSecurity: false
      }
    }
  }
});
```

It did require the additional `webPreferences` layer - but adding this and re-running solced the issue. Cors problem resolved - thanks so much for pointing me to this!

Additional security ramifications understood (as was the case prior) - fortunately, in this case it will be an internal-use only app and is wrapped in additional layers as a result. Thanks again, cheers!

**Comment by IT-MikeS** [comment]
> It did require the additional `webPreferences` layer - but adding this and re-running solved the issue. Cors problem resolved - thanks so much for pointing me to this!

Opps, my bad, but that's what I get for typing on a phone screen 😂

Glad to hear it's working, and yes internal apps are one of the very use cases for turning off `webSecurity`.

I'm going to close this issue, but I will add a docs page explaining this CORS stuff in the near future.

**Comment by digaus** [comment]
@IT-MikeS 
I am using it for reaching smart home devices in the local network. For that I needed  `webSecurity: false` and `app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');`

**Comment by IT-MikeS** [comment]
> @IT-MikeS 
> I am using it for reaching smart home devices in the local network. For that I needed  `webSecurity: false` and `app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');`
> 
> 

As of 1.3.1, you should no longer need the switch as there was a bug in electron with the webSecurity option

**Comment by digaus** [comment]
> > @IT-MikeS
> > I am using it for reaching smart home devices in the local network. For that I needed  `webSecurity: false` and `app.commandLine.appendSwitch('disable-features', 'OutOfBlinkCors');`
> 
> As of 1.3.1, you should no longer need the switch as there was a bug in electron with the webSecurity option

Good to here :)

**Comment by fromage9747** [comment]
Can anyone tell me where I can add `app.commandLine.appendSwitch` for the capacitor electron?

I am trying to add `app.commandLine.appendSwitch('enable-features', 'WebShare');` as it does not work on macOS without web-share enabled in Chrome.

**Comment by jepiqueau** [comment]
@fromage9747 go in the setup.ts and go to the function setupContentSecurityPolicy and add what you need

**Comment by fromage9747** [comment]
@jepiqueau Thank you for getting back to me!

Unfortunately, I do not have `setupContentSecurityPolicy` in my setup.ts...

This is the contents of my setup.ts:
```
import type { CapacitorElectronConfig } from '@capacitor-community/electron';
import {
  CapElectronEventEmitter,
  CapacitorSplashScreen,
  setupCapacitorElectronPlugins,
} from '@capacitor-community/electron';
import chokidar from 'chokidar';
import type { MenuItemConstructorOptions } from 'electron';
import { app, BrowserWindow, Menu, MenuItem, nativeImage, Tray, session } from 'electron';
import electronIsDev from 'electron-is-dev';
import electronServe from 'electron-serve';
import windowStateKeeper from 'electron-window-state';
import { join } from 'path';

// Define components for a watcher to detect when the webapp is changed so we can reload in Dev mode.
const reloadWatcher = {
  debouncer: null,
  ready: false,
  watcher: null,
};
export function setupReloadWatcher(electronCapacitorApp: ElectronCapacitorApp): void {
  reloadWatcher.watcher = chokidar
    .watch(join(app.getAppPath(), 'app'), {
      ignored: /[/\\]\./,
      persistent: true,
    })
    .on('ready', () => {
      reloadWatcher.ready = true;
    })
    .on('all', (_event, _path) => {
      if (reloadWatcher.ready) {
        clearTimeout(reloadWatcher.debouncer);
        reloadWatcher.debouncer = setTimeout(async () => {
          electronCapacitorApp.getMainWindow().webContents.reload();
          reloadWatcher.ready = false;
          clearTimeout(reloadWatcher.debouncer);
          reloadWatcher.debouncer = null;
          reloadWatcher.watcher = null;
          setupReloadWatcher(electronCapacitorApp);
        }, 1500);
      }
    });
}

// Define our class to manage our app.
export class ElectronCapacitorApp {
  private MainWindow: BrowserWindow | null = null;
  private SplashScreen: CapacitorSplashScreen | null = null;
  private TrayIcon: Tray | null = null;
  private CapacitorFileConfig: CapacitorElectronConfig;
  private TrayMenuTemplate: (MenuItem | MenuItemConstructorOptions)[] = [
    new MenuItem({ label: 'Quit App', role: 'quit' }),
  ];
  private AppMenuBarMenuTemplate: (MenuItem | MenuItemConstructorOptions)[] = [
    { role: process.platform === 'darwin' ? 'appMenu' : 'fileMenu' },
    { role: 'viewMenu' },
  ];
  private mainWindowState;
  private loadWebApp;
  private customScheme: string;

  constructor(
    capacitorFileConfig: CapacitorElectronConfig,
    trayMenuTemplate?: (MenuItemConstructorOptions | MenuItem)[],
    appMenuBarMenuTemplate?: (MenuItemConstructorOptions | MenuItem)[]
  ) {
    this.CapacitorFileConfig = capacitorFileConfig;

    this.customScheme = this.CapacitorFileConfig.electron?.customUrlScheme ?? 'capacitor-electron';

    if (trayMenuTemplate) {
      this.TrayMenuTemplate = trayMenuTemplate;
    }

    if (appMenuBarMenuTemplate) {
      this.AppMenuBarMenuTemplate = appMenuBarMenuTemplate;
    }

    // Setup our web app loader, this lets us load apps like react, vue, and angular without changing their build chains.
    this.loadWebApp = electronServe({
      directory: join(app.getAppPath(), 'app'),
      scheme: this.customScheme,
    });
  }

  // Helper function to load in the app.
  private async loadMainWindow(thisRef: any) {
    await thisRef.loadWebApp(thisRef.MainWindow);
  }

  // Expose the mainWindow ref for use outside of the class.
  getMainWindow(): BrowserWindow {
    return this.MainWindow;
  }

  getCustomURLScheme(): string {
    return this.customScheme;
  }

  async init(): Promise<void> {
    const icon = nativeImage.createFromPath(
      join(app.getAppPath(), 'assets', process.platform === 'win32' ? 'appIcon.ico' : 'appIcon.png')
    );
    this.mainWindowState = windowStateKeeper({
      // defaultWidth: 412, // development sizes
      // defaultHeight: 660, // development sizes
      defaultWidth: 268, // Prod Small Size
      defaultHeight: 513, // Prod Small Size
      // defaultWidth: 1000,
      // defaultHeight: 800,
    });
    // Setup preload script path and construct our main window.
    const preloadPath = join(app.getAppPath(), 'build', 'src', 'preload.js');
    this.MainWindow = new BrowserWindow({
      icon,
      show: false,
      x: this.mainWindowState.x,
      y: this.mainWindowState.y,
      width: this.mainWindowState.width,
      height: this.mainWindowState.height,
      resizable: false,
      alwaysOnTop: true,
      // focusable: false,
      closable: true,
      fullscreenable: false,
      maximizable: false,
      frame: false,
      webPreferences: {
        nodeIntegration: true,
        contextIsolation: true,
        enableBlinkFeatures: "WebContentsForceDark",
        experimentalFeatures: true,
        // Use preload to inject the electron variant overrides for capacitor plugins.
        // preload: join(app.getAppPath(), "node_modules", "@capacitor-community", "electron", "dist", "runtime", "electron-rt.js"),
        preload: preloadPath,
      },
    });
    this.mainWindowState.manage(this.MainWindow);

    if (this.CapacitorFileConfig.backgroundColor) {
      this.MainWindow.setBackgroundColor(this.CapacitorFileConfig.electron.backgroundColor);
    }

    // If we close the main window with the splashscreen enabled we need to destory the ref.
    this.MainWindow.on('closed', () => {
      if (this.SplashScreen?.getSplashWindow() && !this.SplashScreen.getSplashWindow().isDestroyed()) {
        this.SplashScreen.getSplashWindow().close();
      }
    });

    // When the tray icon is enabled, setup the options.
    if (this.CapacitorFileConfig.electron?.trayIconAndMenuEnabled) {
      this.TrayIcon = new Tray(icon);
      this.TrayIcon.on('double-click', () => {
        if (this.MainWindow) {
          if (this.MainWindow.isVisible()) {
            this.MainWindow.hide();
          } else {
            this.MainWindow.show();
            this.MainWindow.focus();
          }
        }
      });
      this.TrayIcon.on('click', () => {
        if (this.MainWindow) {
          if (this.MainWindow.isVisible()) {
            this.MainWindow.hide();
          } else {
            this.MainWindow.show();
            this.MainWindow.focus();
          }
        }
      });
      this.TrayIcon.setToolTip(app.getName());
      this.TrayIcon.setContextMenu(Menu.buildFromTemplate(this.TrayMenuTemplate));
    }

    // Setup the main menu bar at the top of our window.
    Menu.setApplicationMenu(Menu.buildFromTemplate(this.AppMenuBarMenuTemplate));

    // If the splashscreen is enabled, show it first while the main window loads then switch it out for the main window, or just load the main window from the start.
    if (this.CapacitorFileConfig.electron?.splashScreenEnabled) {
      this.SplashScreen = new CapacitorSplashScreen({
        imageFilePath: join(
          app.getAppPath(),
          'assets',
          this.CapacitorFileConfig.electron?.splashScreenImageName ?? 'splash.png'
        ),
        windowWidth: 400,
        windowHeight: 400,
      });
      this.SplashScreen.init(this.loadMainWindow, this);
    } else {
      this.loadMainWindow(this);
    }

    // Security
    this.MainWindow.webContents.setWindowOpenHandler((details) => {
      if (!details.url.includes(this.customScheme)) {
        return { action: 'deny' };
      } else {
        return { action: 'allow' };
      }
    });
    this.MainWindow.webContents.on('will-navigate', (event, _newURL) => {
      if (!this.MainWindow.webContents.getURL().includes(this.customScheme)) {
        event.preventDefault();
      }
    });

    // Link electron plugins into the system.
    setupCapacitorElectronPlugins();

    // When the web app is loaded we hide the splashscreen if needed and show the mainwindow.
    this.MainWindow.webContents.on('dom-ready', () => {
      if (this.CapacitorFileConfig.electron?.splashScreenEnabled) {
        this.SplashScreen.getSplashWindow().hide();
      }
      if (!this.CapacitorFileConfig.electron?.hideMainWindowOnLaunch) {
        this.MainWindow.show();
      }
      setTimeout(() => {
        if (electronIsDev) {
          this.MainWindow.webContents.openDevTools();
        }
        CapElectronEventEmitter.emit('CAPELECTRON_DeeplinkListenerInitialized', '');
      }, 400);
    });
  }
}

// Set a CSP up for our application based on the custom scheme
export function setupContentSecurityPolicy(customScheme: string): void {
  session.defaultSession.webRequest.onHeadersReceived((details, callback) => {
    callback({
      responseHeaders: {
        ...details.responseHeaders,
        'Content-Security-Policy': [
          electronIsDev
            ? `default-src ${customScheme}://* 'unsafe-inline' devtools://* 'unsafe-eval' data:; img-src * 'self' blob: data:; default-src *; style-src 'self' 'unsafe-inline'; script-src * 'self' 'unsafe-inline' 'unsafe-eval'; media-src * 'self' blob: data:; connect-src * 'self' data:;`
            : `default-src ${customScheme}://* 'unsafe-inline' data:; img-src * 'self' blob: data:; default-src *; style-src 'self' 'unsafe-inline'; script-src * 'self' 'unsafe-inline' 'unsafe-eval'; media-src * 'self' blob: data:; connect-src * 'self' data:;`
        ],
      },
    });
  });
}

```

**Comment by jepiqueau** [comment]
@fromage9747 if you look at 14 last lines of what you sent to me it is there

**Comment by fromage9747** [comment]
@jepiqueau Well I'll be damned...  I guess I can't rely on vscode search any more.

Cheers!

**Comment by fromage9747** [comment]
@jepiqueau 

Just to confirm, I would add it like so?

![image](https://github.com/capacitor-community/electron/assets/23147783/058962c7-b59e-43b2-aa20-601bdfafbc5a)


I was under the impression that this section was only for the CSP that you would normally include in the index.html.

![image](https://github.com/capacitor-community/electron/assets/23147783/c89db4e1-c96b-4a2c-8653-f5182bfacf36)

I am trying to enable this:
chrome://flags/#web-share
![image](https://github.com/capacitor-community/electron/assets/23147783/8edd9d3a-a6b9-40f5-9fdc-c39a833b3577)

Only trying to confirm as I have added it as per the above screenshot and the result is the same as when it's disabled in my browser.

**Comment by jepiqueau** [comment]
@fromage9747 so sorry i do not really know
