### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by narenpublic** [capacitor-community/electron#64]
Are the docs going to be updated soon from the "coming soon" -- looking for the ts config options for createCapacitorElectronApp()

thnx

**Comment by IT-MikeS** [comment]
They are being worked on actively, however if you set your line in the `index.ts` to look like `const myCapacitorApp = createCapacitorElectronApp({});` and place your cursor between the curly braces and hit `CTRL+SPACE` the intellisense should give you options in visual studio code for example.

**Comment by narenpublic** [comment]
@IT-MikeS thanks for the quick reply.  One more quick question, if I want access to  ipcRenderer in my app ts, how do I get at that?

**Comment by IT-MikeS** [comment]
Just as an update, I have add the config options docs this morning.
