### ISSUE TITLE
Help Contributors getting started

### ISSUE THREAD

**Issue by gnesher** [capacitor-community/electron#66]
Hi,

The contributing guidelines (https://github.com/capacitor-community/electron/blob/main/CONTRIBUTING.md) are currently a place holder and there are no obvious 'entry points' for new contributors (easy bugs to fix, small enchantments etc.) It would be great if we could set something up to help people get started

**Comment by IT-MikeS** [comment]
For the most part, things to start on are either from your own head, or from issue tags.

Things like adding to the docs, and general code clean up are always needed.

I agree the documentation on contributing is lacking, I plan to have a "clean up session" soon to address some of the outstanding oversights and lackings in the repo, but my 9to 5 hasn't been so 9 to 5 lately and more like 7 to 7 🙃

One day I hope I can work on open source full time 😜

**Comment by gnesher** [comment]
@IT-MikeS yes that seems to be the general situation for many of us since Covid-19 started... Anyhow, I'd be happy to try and help if someone would point me to specific tasks. Writing documentation is a little difficult as our usage is very simple at the moment so it's a little difficult to write something extensive.

**Comment by IT-MikeS** [comment]
This will be easier in 3.0
