### ISSUE TITLE
Accept file::// urls

### ISSUE THREAD

**Issue by vespasianvs** [capacitor-community/electron#67]
**Is your feature request related to a problem? Please describe.**
For the product I am working on, I am now using a custom build of capacitor-community/electron as we need the filesystem aspect to be able to accept file:// urls. Currently it works by not passing in a directory at all, which triggers my code to check if there is a valid URL and whether the protocol is file://. Is this something useful for the main project? I have tested my code for file and directory reading but it probably needs some more testing around some other areas of filesystem.ts, e.g. mkdir etc. I can try to get around to finding some time to do that! Let me know if you want a PR for what I have.

**Comment by IT-MikeS** [comment]
Can you describe the use case more? 

I don't understand where you would need to use a file directory URL rather than just reading the file on the system via the Electrons API.

**Comment by vespasianvs** [comment]
So we're using deep linking within our electron app and as part of that a file url can be passed in via the query. I did at first just try removing the file protocol and accessing the directory path but the current API only allows directories to be Documents or 'DRIVE_ROOT' - neither of which worked well for us (access denied errors and having to do string manipulation to try to find the correct place and drive, which wasn't reliable - Node seems to default to the drive that node is running on), the file:// url seemed to offer is the most consistent and reliable way of doing this and works consistently across platforms. It is also fully supported by NodeFS so it's nice to be able to have this as an option in Electron.

**Comment by IT-MikeS** [comment]
Have you tried to load the file via the electron API directly rather than plugins? 

You could even make your own electron platform plugin that would do what you need too.

**Comment by vespasianvs** [comment]
I'll have a play. I did try it via the electron API, but because that uses the HTML5 Web API, I was then getting security issues using the file:// urls (even though we're on https). I will have a play with perhaps doing a plugin if I can find time around the day job :)

For now we'll probably keep using the custom version of community electron that I have and I'll just keep my fork up to date with yours.
