### ISSUE TITLE
Can not add platform with Yarn2/PnP

### ISSUE THREAD

**Issue by xenoterracide** [capacitor-community/electron#68]
```
> yarn cap add @capacitor-community/electron                                                     # ppm -> 1-setup |• — ! + ?
[error] platform @capacitor-community/electron not found
```
```
> yarn info -A @capacitor-community/electron                                                     # ppm -> 1-setup |• — ! + ?
└─ @capacitor-community/electron@npm:1.3.1
   ├─ Version: 1.3.1
   │
   └─ Dependencies
      ├─ @capacitor/core@npm:^2.0.0 → npm:2.4.2
      ├─ chalk@npm:^4.1.0 → npm:4.1.0
      ├─ electron-is-dev@npm:^1.2.0 → npm:1.2.0
      ├─ electron-serve@npm:^1.0.0 → npm:1.0.0
      ├─ fs-extra@npm:^8.1.0 → npm:8.1.0
      ├─ mime-types@npm:~2.1.27 → npm:2.1.27
      └─ ora@npm:^4.0.4 → npm:4.1.1
```

might be related to this which I opened, but since the error is different https://github.com/ionic-team/capacitor/issues/3805

**Comment by IT-MikeS** [comment]
It looks like you  haven't install the community platform first, below are the steps from the docs.

Let me know if this doesn't fix the issue

1. Build your webapp in your capacitor initiated project ('npm run build' for example).
2. Run `npm i @capacitor-community/electron` in your webapp project directory. This will install the platform for use with the `@capacitor/cli`.
3. Run `npx cap add @capacitor-community/electron` to initiate the platform, this will create the electron folder in your webapp project.
4. Run `npx cap open @capacitor-community/electron` to start your app in electron.

**Comment by xenoterracide** [comment]
yes, I tried that, that's why  included the output of `yarn info -A @capacitor-community/electron` to show that it was installed

```
> yarn workspace @ppm/frontend add --dev @capacitor-community/electron                                # ppm -> 1-setup ! + ?
➤ YN0000: ┌ Resolution step
➤ YN0002: │ eslint-plugin-unused-imports@npm:1.0.0 doesn't provide @typescript-eslint/parser@^4.0.0 requested by @typescript-eslint/eslint-plugin@npm:4.7.0
➤ YN0002: │ @aurelia/ts-jest@npm:0.8.0-dev.202011152346 doesn't provide jest@>=26 <27 requested by ts-jest@npm:26.4.4
➤ YN0002: │ @aurelia/ts-jest@npm:0.8.0-dev.202011152346 doesn't provide typescript@>=3.8 <5.0 requested by ts-jest@npm:26.4.4
➤ YN0000: └ Completed in 0s 329ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 4s 39ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 3s 170ms
➤ YN0000: Done with warnings in 8s 79ms
> yarn workspace @ppm/frontend cap add @capacitor-community/electron                                  # ppm -> 1-setup ! + ?
[error] platform @capacitor-community/electron not found
>                                                     
```
npm/npx isn't going to work with yarn 2 PnP.

**Comment by IT-MikeS** [comment]
Yes the package looks directly at `node_modules`

Please note at this time only `npm/npx` is officially supported by this platform, however `yarn 1` should work but it has not been tested.

Open to PR's to add support for others

**Comment by merceyz** [comment]
> Yes the package looks directly at node_modules

Why though? `require.resolve` exists for a reason

**Comment by IT-MikeS** [comment]
> > Yes the package looks directly at node_modules
> 
> Why though, isn't `require.resolve` able to do what you need?

It very well may be what is needed, however after looking this over again, this problem mainly exists in the Capacitor CLI itself, the reason the error is different is because the process in which community platforms are installed is different from the built in ones.

I will mark this external cause and will review the issue again once the CLI supports these other package managers.

**Comment by IT-MikeS** [comment]
This should get resolved in the changes planned for v3

**Comment by IT-MikeS** [comment]
This is resolved in v3 so I will close this for now
