### ISSUE TITLE
Custom url scheme for CORS purpose

### ISSUE THREAD

**Issue by inatnun** [capacitor-community/electron#71]
**Is your feature request related to a problem? Please describe.**
I want to config my custom scheme for CORS purpose, I don't want to use default one with capacitor-electron://

**Describe the solution you'd like**
I want to have the way to override the default scheme with mine (I know about deeplinks but it doesn't fit my using), I have tried to use the deeplinks solution but it doesn't change the fact that the origin of app still be capacitor-electron://

**Describe alternatives you've considered**
I think you can define loadWebApp inside init function or constructor then reading scheme and directory from config
`const loadWebApp = electronServe({
  directory: config.directory,
  scheme: config.scheme,
});`

**Additional context**
If you OK, I can create pull request for doing this thing. or if you have another solution, please feel free to contact me

**Comment by IT-MikeS** [comment]
This will most likely make it into the 2.0 release which will come along side Capacitor 3.

How it will work will be similar to what you have suggested here but more in line with what Capacitor 3 is going to be doing on other platforms.

**Comment by coreyjv** [comment]
@IT-MikeS -- I've started exploring the 3.0 betas and the origin is still `capacitor-electron://`. 

Do you have a suggested solution for exposing this customization? Would it be a pattern similar to `createCapacitorElectronDeepLinking` or an option on `createCapacitorElectronApp`? I wouldn't mind contributing a PR to get this feature in but want it to be in line with what you're thinking.

Thanks!

**Comment by IT-MikeS** [comment]
I just added a couple of things that do this but they are still in testing and not in the released builds.

- 1b2e02f2a6a95bb8bd23f03a29ee4854b5982346
- 8dd30a3a4dd0422d430cbd879fa338ff212b02ad

**Comment by coreyjv** [comment]
Awesome, thanks for the update @IT-MikeS !
