### ISSUE TITLE
capacitor:add @capacitor-community/electron fails on BigSur

### ISSUE THREAD

**Issue by michi7801** [capacitor-community/electron#73]
# Problem
Today I tried to install the @capacitor-community/electron package. The installation works fine at first, but when I try to "npx cap add @capacitor-community/electron" I get the following error:

```bash
> @capacitor-community/electron@1.3.2 capacitor:add
> node dist/cap-scripts.js add

✖ Adding Electron platform: The "path" argument must be of type string. Received undefined
node:internal/process/promises:225
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:278:15)
    at validateString (node:internal/validators:123:11)
    at Object.join (node:path:1039:7)
    at Object.i [as getCwd] (/Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:2:521)
    at a (/Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:6:197)
    at Object.n [as doAdd] (/Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:6:960)
    at /Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:363
    at Object.g [as runTask] (/Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:2:1902)
    at i (/Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:311)
    at /Users/user/project/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:718 {
  code: 'ERR_INVALID_ARG_TYPE'
}
npm ERR! code 1
npm ERR! path /Users/user/project/node_modules/@capacitor-community/electron
npm ERR! command failed
npm ERR! command sh -c node dist/cap-scripts.js add

npm ERR! A complete log of this run can be found in:
npm ERR!    /Users/user/.npm/_logs/2020-12-11T06_57_03_068Z-debug.log
```

# Environment

- MacOS BigSur 11.0.1
- @capacitor/cli version: 2.4.4
- @capacitor/core version 2.4.4

**Comment by IT-MikeS** [comment]
What is the project you are trying to add it to? (React Ionic, Vue, ect. )

I have not tested BigSur as of yet but I hope to have my machine updated soon and begin testing.

**Comment by michi7801** [comment]
It is just a plain HTML, CSS and JavaScript project. (For now) there is no Framework!

**Comment by ri0t** [comment]
I second this (probably) on Debian Linux (sid) with a very recent ionic project:

```
➜ npx cap add @capacitor-community/electron

> @capacitor-community/electron@1.3.2 capacitor:add
> node dist/cap-scripts.js add

✖ Adding Electron platform: The "path" argument must be of type string. Received undefined
(node:4818) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:1039:7)
    at Object.i [as getCwd] (/home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:2:521)
    at a (/home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:6:197)
    at Object.n [as doAdd] (/home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:6:960)
    at /home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:363
    at Object.g [as runTask] (/home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:2:1902)
    at i (/home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:311)
    at /home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:718
    at Object.parcelRequire.Focm../common (/home/user/src/frontend/node_modules/@capacitor-community/electron/dist/cap-scripts.js:12:915)
(node:4818) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4818) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Environment
* Debian Linux Sid
* node v12.19.0
* npm 7.1.0
* capacitor-community/electron@1.3.2
* capacitor/android@2.4.1
* capacitor/cli@2.4.1
* capacitor/core@2.4.1

**Comment by kanatzidis** [comment]
I experienced this too. For me, it was because I was running an old version of node/npm that did not yet support the `INIT_CWD` env var (introduced in [v5.4.0](https://github.com/npm/cli/blob/ab0f0260e5b6333f98062fb2d9f4f9954d3ee6cd/changelogs/CHANGELOG-5.md#v540-2017-08-22)). This was causing [this line](https://github.com/capacitor-community/electron/blob/main/cap-scripts/common.ts#L48) to fail because it asserts non-null.

@michi7801 didn't post their npm version so I can't be 100% sure, but I'd bet this is the problem @ri0t is experiencing as well because the variable was [accidentally removed](https://github.com/npm/cli/issues/2033) in npm v7 and only re-added in v7.1.2.

Updating my npm locally allowed `cap add` to run successfully.

**Comment by ri0t** [comment]
Aye, updating npm to 7.3 resolved the above issue. Now it claims, it couldn't find capacitor.config.json - which is exactly where it should be :)

**Comment by IT-MikeS** [comment]
I'll dig into this more and make note of a required npm version in docs when I find the minimum version.

**Comment by danimateo** [comment]
If you are still having problems with the config not being found, in my case at least, i ran the cap command from a shell script that was being spawned from node and it passed on the process.env along with the INIT_CWD which was not being overwritten and remained the main dir instead of the @capacitor-community/electron dir that should have been used. 

My solution was to unset INIT_CWD in the shell script before running this. Hope it helps, your case seems oddly similar. And @IT-MikeS , maybe look into another method to get the path?

**Comment by frederickjjoubert** [comment]
Hey guys, I'm running `npx cap add @capacitor-community/electron` within my project root directory and getting the `capacitor.config.json` error. At first I was also getting the path error, but updating npm to 7.4.3 fixed the path error and now I'm getting the new error I just mentioned.

I'm trying to add electron to my Ionic (w/ Angular) Capacitor project.

**Comment by rodydavis** [comment]
Error was happening for me if I had a space in my project name
