### ISSUE TITLE
Build Windows on Mac

### ISSUE THREAD

**Issue by LuizTokuhara** [capacitor-community/electron#79]
**Describe the bug**
Started a clean project and tried to build for windows using Mac (10.15.7 Catalina).

> cannot build native dependency  reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible
                                    cause=exit status 1
                                    errorOut=prebuild-install info begin Prebuild-install version 6.0.0

> prebuild-install WARN install prebuilt binaries enforced with --force!
    prebuild-install WARN install prebuilt binaries may be out of date!
    prebuild-install info looking for cached prebuild @ /Users/xxx/.npm/_prebuilds/90c5a2-sharp-v0.27.0-electron-v85-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-electron-v85-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-electron-v85-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=11.2.0 runtime=electron arch=x64 libc= platform=win32)

- OS: Mac Os Catalina
- Capacitor/Electron: 1.3.1
- Electron: 11.0.1
- Electron-builder: 22.9.1

**Comment by IT-MikeS** [comment]
> cannot build native dependency reason=prebuild-install failed with error and build from sources not possible because platform or arch not compatible

> prebuild-install http 404 https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-electron-v85-win32-x64.tar.gz

> prebuild-install http request GET https://github.com/lovell/sharp/releases/download/v0.27.0/sharp-v0.27.0-electron-v85-win32-x64.tar.gz

The prebuilt data your mac needs to build a windows app is not available (404), and because `electron-builder` can not build from source for windows on a mac, it fails.

This would be an issue to bring up over at the `electron-builder` repo.

I'm afraid I'm unable to help with this issue from this repo.
