### ISSUE TITLE
Source Maps  "Unexpected end of JSON input" in main BrowserWindow

### ISSUE THREAD

**Issue by ari62** [capacitor-community/electron#82]
**Describe the bug**
I am seeing many messages like the following in my BrowserWindow's DevTools console: 

`DevTools failed to load SourceMap: Could not parse content for capacitor-electron://-/17-es2015.js.map: Unexpected end of JSON input`
`DevTools failed to load SourceMap: Could not parse content for capacitor-electron://-/default~firebase-auth~pages-social-profile-profile-module-es2015.js.map: Unexpected end of JSON input`
`DevTools failed to load SourceMap: Could not parse content for capacitor-electron://-/swipe-back-2154c9a7-js-es2015.js.map: Unexpected end of JSON input`
`DevTools failed to load SourceMap: Could not parse content for capacitor-electron://-/5-es2015.js.map: Unexpected end of JSON input`
`DevTools failed to load SourceMap: Could not parse content for capacitor-electron://-/28-es2015.js.map: Unexpected end of JSON input
`

In my tsconfig.json file I tried all combinations of :  
```
  "sourceMap": true,
    "inlineSourceMap": true,
    "inlineSources": true
```

**To Reproduce**
 I see the messages on startup of my app.

**Expected behavior**
No messages about source maps.

**Desktop (please complete the following information):**

- OS: mac osx

I am not sure if this is a bug or if I am doing something wrong.

**Comment by IT-MikeS** [comment]
This is already a documented issue, and is caused by electron itself. 

Please see this issue for more info.
https://github.com/capacitor-community/electron/issues/46
