### ISSUE TITLE
404 when trying to load bundle.js from webpack

### ISSUE THREAD

**Issue by RandomEngy** [capacitor-community/electron#84]
404 when trying to load bundle.js from webpack. It is trying to load from capacitor-electron://-/bundle.js

**To Reproduce**

1. Create a project with webpack, building to dist folder with bundle.js
2. Include your page with index.html in dist folder with `<script src="bundle.js"></script>`
3. Set up capacitor.config.json with webDir: "dist"
4. `npx cap add @capacitor-community/electron`
5. `npx cap open @capacitor-community/electron`

**Expected behavior**
Page launches and loads bundle.js

**Screenshots**
![image](https://user-images.githubusercontent.com/9450861/106712729-38683380-65ae-11eb-85a6-188643993d35.png)

![image](https://user-images.githubusercontent.com/9450861/106712896-7d8c6580-65ae-11eb-8e02-e0c17a745142.png)

- OS: Windows 10 version 2004

**Comment by IT-MikeS** [comment]
Ah this is a silly thing, `<script src="bundle.js"></script>` needs to be `<script src="/bundle.js"></script>` the internals of the platform basically operate like a webserver, so it needs a root ref in the script tag. Normally frameworks like Vue or React take care of this in bootstrapping but with a manual project it must be done explicitly

**Comment by RandomEngy** [comment]
Thanks. Turns out that "bundle.js" works just fine. I had just neglected to run the "copy" command to update my website files. I made a PR to call this out to other dummies like me from bothering you:

https://github.com/capacitor-community/electron/pull/86
