### ISSUE TITLE
How to easily build and distribute on stores with capacitor electron ? (Microsoft store, OSX, Chrome)

### ISSUE THREAD

**Issue by Aarbel** [capacitor-community/electron#87]
Distributing Electron desktop apps is a big pain, especially on Microsoft store.
Updating these apps are also a big thing, autoUpdater work differently on different devices. Specific certificates are necessary on Microsoft, etc....

How do you distribute new versions of your desktop apps with Capacitor in a blink ? 

Thanks a lot !

**Comment by IT-MikeS** [comment]
A more seem-less way of doing OTA type updates for electron apps would be great and I am kinda poking at it, but check out `electron-builder` and `electron-windows-store` and see if those at least aid you in distribution.

**Comment by Aarbel** [comment]
@IT-MikeS `electron-builder` and `electron-windows-store` are really heavy with a lot of configs needed to build on stores

**Comment by IT-MikeS** [comment]
They are yes, but unfortunately they are really the only good options for electron apps at the time. 

I do know they are really open to suggestions to make the tools better, so if you have any ideas on how to streamline the processes they do, or how to slim down the install base of the apps, I'm sure they'd love to hear it over on their respective repos 🚀

**Comment by Aarbel** [comment]
a tool like Appflow would be the best

**Comment by Aarbel** [comment]
And also a simple medium article about Electro build / distribution on all stores

**Comment by IT-MikeS** [comment]
A tool like AppFlow would be great but that's a really tall order for the time I currently have in my free time outside of my 9-5, but someone else is always free to build such a tool.

As for the article, there are plenty out there including some great video tutorials on building electron apps into store or other distributions, and my tutorial writing is rusty at best when you compare it to some of the awesome guide writers out there.

**Comment by Aarbel** [comment]
@IT-MikeS you should really talk with https://todesktop.com/, they provide a standard api / builder for desktop apps https://docs.todesktop.com/

**Comment by Aarbel** [comment]
It's really easy to use and powerfull, could be awesome to share the same apis
