### ISSUE TITLE
Add method of adding to preload

### ISSUE THREAD

**Issue by 00drip** [capacitor-community/electron#90]
There is currently no way to add code to the preload without creating a plugin. Changing the `preloader.js` file works, but the changes are overwritten on every `cap sync`.

It would be nice to be able to add code, such as `contextBridge.exposeInMainWorld` calls, to the preloader without the large boilerplate associated with making a plugin.

**Comment by IT-MikeS** [comment]
As of 1.3.4, a file `user-preload-script.js` is located in the `electron` directory, this will get added into the regular preload. Version 3 will also make this easier on users
