### ISSUE TITLE
Deeplinking not working 

### ISSUE THREAD

**Issue by vilasp** [capacitor-community/electron#92]
**Describe the bug**
I've created a Capacitor application with Oauth2 (Okta, AppAuth-js) which runs fine on IOS and in the browser. Now trying with Electron using this package and deeplinking I'm getting an error which I can't really figure out. I've set up the electron app with deeplinking according to the [documentation](https://capacitor-community.github.io/electron/#/./deeplinking/index). 

```javascript
const myCapacitorApp = createCapacitorElectronApp()
createCapacitorElectronDeepLinking(myCapacitorApp, {
  customProtocol: 'electronboogie',
  customHandler: url => {
    console.log('The url: ' + url)
  }
})
```
i've also added the following code to listen for the URL open call inside my Capacitor app

```javascript
 App.addListener('appUrlOpen', (data: any) => {
        console.log('dataurl: ' + data.url)
      })
```
I Run the application using `npx cap open @capacitor-community/electron` and opening the window to the Okta Authorization server works well but when Okta tries to redirect me back to the application using `electronboogie://callback` as redirect url i get the following error message

![image](https://user-images.githubusercontent.com/5450557/111819851-1e29b100-88e1-11eb-95fc-05e190eb8267.png)

Any idea about what could be wrong?

**To Reproduce**
Hard to reproduce the entire setup but i could try if no other option. 

I'm running the following commands when starting the electron app,
1. `npm run build`
2. `npx cap copy @capacitor-community/electron`
3. `npx cap open @capacitor-community/electron`

**Expected behavior**
Expect the deeplink to be fired and the electron app to send the Url to the initiating browser window

**Screenshots**
added in the description 

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chromium 
- Version 1.3.4

**Additional context**
Nothing else to add

**Comment by IT-MikeS** [comment]
Deeplinking requires the app to be compiled and installed, you'll need to build the electron app for your OS so the OS can register the program as the association for the custom protocol

**Comment by polisettyManoj** [comment]
@vilasp deeplinking issue is fixed for you ? 

 App.addListener('appUrlOpen', (data: any) => {
        console.log('dataurl: ' + data.url)
      })


this method is giving correct URL ?
