### ISSUE TITLE
Unable to add Electron if there is a space in the parent folder name

### ISSUE THREAD

**Issue by priteshbonde** [capacitor-community/electron#95]
**Describe the bug**
I have an Angular Ionic app with Capacitor integrated to it. I am referring the [documentation](https://capacitor-community.github.io/electron/#/./getting-started/index). 
When I run command `npx cap add @capacitor-community/electron` i get below error
```

> node dist/cap-scripts.js add

⠙ Adding Electron platformError: undefined
✖ Adding Electron platform: 
(node:4502) UnhandledPromiseRejectionWarning: /bin/sh: line 0: cd: /Users/priteshbonde/Code: No such file or directory

(node:4502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

if you observed line `(node:4502) UnhandledPromiseRejectionWarning: /bin/sh: line 0: cd: /Users/priteshbonde/Code: No such file or directory` that truncated the rest of the repo URL.

```
**To Reproduce**

1. Create a Angular ionic application with a parent folder have a `space` in the name example `code repository/electronAPP`
2. Open Terminal
3.  Run `npm i @capacitor-community/electron` 
4. Run `npx cap add @capacitor-community/electron`

**Expected behaviour**
No matter what the repo url is the electron app should be created in the app. 

**Screenshots**
     
![image](https://user-images.githubusercontent.com/8036581/115988977-8f900a00-a5d9-11eb-8576-ef94f322d7e7.png)

**Desktop (please complete the following information):**

- OS: MAC OS Big Sur
- Angular 11, Ionic 5, capacitor 2

FYI I was able to resolve the issue by removing the space in the parent folder name but ideally i think that the package should handle this scenario.

**Comment by IT-MikeS** [comment]
Good catch, turns out its a node thing with `exec` its corrected now in v1.4.2
