### ISSUE TITLE
Getting "capacitor.config.json does not exist, did you setup capacitor in your project root?" error using ionic

### ISSUE THREAD

**Issue by Jacob-Mahoney** [capacitor-community/electron#98]
**Describe the bug**
Getting an error saying: "capacitor.config.json does not exist, did you setup capacitor in your project root?" after trying to run the `npx cap add @capacitor-community/electron` command.

**To Reproduce**

1. `ionic start project blank --type=angular --capacitor`
2. `cd project`
3. `npm i --legacy-peer-deps` (since I'm using npm v7)
4. `ionic integrations enable capacitor`
5. `npm i @capacitor-community/electron`
6. `ionic build`
7. `npx cap add @capacitor-community/electron`
8. See error

**Expected behavior**
The command to run successfully.

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: N/A
- Version: 1.4.2

**Comment by IT-MikeS** [comment]
What version of capacitor are you using, `npm ls @capacitor/core`

**Comment by Jacob-Mahoney** [comment]
> What version of capacitor are you using, `npm ls @capacitor/core`
> 
> If it's v3, you need to use `npm i @capacitor-community/electron@next`

Yep, this worked! Thank you Mike!
